import {useEffect,useRef,useState} from 'react';
import './RdcPrefixAtlas.css';
import './RdcRelationStudy.css';

const API='http://127.0.0.1:5001/api/rdc-relation';
const fmt=x=>x===undefined||x===null?'—':Number(x).toPrecision(6);
async function get(path){const r=await fetch(API+path);if(!r.ok){const e=await r.json().catch(()=>({detail:r.statusText}));throw new Error(e.detail||r.statusText);}return r.json();}
const relations=['nsubj','obj','iobj','obl','nmod','amod','advmod','advcl','acl','conj','compound','case','mark','det'];

function Field({data}){
  const ref=useRef(null);const [picked,setPicked]=useState(null),[mapping,setMapping]=useState('signed-log');
  useEffect(()=>{if(!data?.values?.length||!ref.current)return;const el=ref.current,rows=data.values.length,cols=data.values[0].length;el.width=cols;el.height=rows;const ctx=el.getContext('2d'),im=ctx.createImageData(cols,rows),limit=data.whole_field_absmax||1;
    for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const a=data.values[y][x];const v=mapping==='linear'?a/limit:Math.sign(a)*Math.log1p(Math.abs(a)/.01)/Math.log1p(limit/.01),s=Math.min(Math.abs(v),1),i=(y*cols+x)*4;im.data[i]=Math.round(v>=0?247:247-205*s);im.data[i+1]=Math.round(248-152*s);im.data[i+2]=Math.round(v<0?250:250-216*s);im.data[i+3]=255;}ctx.putImageData(im,0,0);
  },[data,mapping]);
  if(!data)return <p aria-live="polite">选择记录后载入完整坐标。矩阵需点击“重算矩阵切片”。</p>;
  return <div className="prefix-field"><p>{data.normalization}</p><div className="prefix-controls"><label>颜色映射<select value={mapping} onChange={e=>setMapping(e.target.value)}><option value="signed-log">带符号 log1p（尺度0.01）</option><option value="linear">线性</option></select></label><span>色标 ±{fmt(data.whole_field_absmax)} · 数组宽度{data.native_width} · 列[{data.start},{data.end})</span></div>
    <canvas ref={ref} aria-label="完整原生坐标热力图" data-testid="relation-field" style={{height:Math.max(160,Math.min(560,data.values.length*13))}} onClick={e=>{const b=e.currentTarget.getBoundingClientRect(),x=Math.min(data.values[0].length-1,Math.floor((e.clientX-b.left)/b.width*data.values[0].length)),y=Math.min(data.values.length-1,Math.floor((e.clientY-b.top)/b.height*data.values.length));setPicked({data,row:data.labels[y],coordinate:data.start+x,value:data.values[y][x]});}}/>
    <p className="prefix-muted">纵轴：{data.labels[0]} → {data.labels.at(-1)}。缩略显示会重采样像素；坐标顺序不变，点击或缩小列范围读取原值。</p>
    {picked?.data===data&&<output>{picked.row}，坐标{picked.coordinate} = {picked.value}</output>}{data.download&&<a href={'http://127.0.0.1:5001'+data.download}>下载此样本完整BF16位保真数组</a>}
  </div>;
}

function Metrics({summary}){
  const rows=[...(summary?.probability||[]).filter(r=>r.split==='test'),...(summary?.confirmation_probability||[])];
  return <section><h2>冻结规则与完整词表</h2><p>候选共享训练/验证划分；六条历史增强路线选择零历史权重。KL覆盖全部151,936词表项，一致率不是语义正确率。</p><div className="prefix-table"><table><thead><tr>{['材料','输入范围','候选','KL','argmax一致率'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.split+r.scope+r.route}><td>{r.split}</td><td>{r.scope}</td><td>{r.route}</td><td>{fmt(r.KL)}</td><td>{fmt(r.argmax_agreement)}</td></tr>)}</tbody></table></div><details><summary>训练选择、容量对照与来源置信区间</summary><pre>{JSON.stringify({choices:summary?.choices,matchedDF:summary?.rules?.matched_effective_df,gains:summary?.rules?.paired_test_comparisons,temporal:summary?.dynamics?.paired_temporal_test_gains},null,2)}</pre></details></section>;
}

function ScaleViewer(){
  const [model,setModel]=useState('qwen14'),[samples,setSamples]=useState([]),[sample,setSample]=useState(''),[field,setField]=useState('late'),[value,setValue]=useState(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;get('/scale-samples?model='+model).then(x=>{if(active){setSamples(x);setSample(x[0]?.sample_id||'');setValue(null);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[model]);
  const identity=JSON.stringify([model,sample,field]),current=value?.identity===identity?value:null;
  async function query(){try{const x=await get('/scale-field?'+new URLSearchParams({model,sample,field}));setValue({...x,identity});setError('');}catch(e){setValue(null);setError(e.message);}}
  return <section><h2>三个模型的原生全坐标记录</h2><p>同一来源不意味着同一分词或坐标含义。较大模型保留四个锚点位置；生成过程保留全坐标误差、全部文本与四份完整逐步状态。未采集部分不会伪装为已有数据。</p><div className="prefix-controls"><label>模型<select value={model} onChange={e=>{setModel(e.target.value);setValue(null);}}>{['qwen4','qwen14','glm4'].map(x=><option key={x}>{x}</option>)}</select></label><label>来源<select value={sample} onChange={e=>{setSample(e.target.value);setValue(null);}}>{samples.map(r=><option key={r.sample_id}>{r.sample_id}</option>)}</select></label><label>状态<select value={field} onChange={e=>{setField(e.target.value);setValue(null);}}>{['early','late','generation_early','generation_late','generation_errors'].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={!sample} onClick={query}>读取该模型完整坐标</button></div>{error&&<p role="alert">{error}</p>}<Field data={current?.field}/>{current&&<details><summary>真实文本、分词对齐、原生续写与数值配置</summary><pre>{JSON.stringify({runtime:current.runtime,record:current.record,generation:current.generation},null,2)}</pre></details>}</section>;
}

function ScalarViewer(){
  const [samples,setSamples]=useState([]),[sample,setSample]=useState(''),[anchor,setAnchor]=useState(0),[unit,setUnit]=useState(19),[input,setInput]=useState(17),[output,setOutput]=useState(23),[data,setData]=useState(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;get('/samples?scope=fresh').then(x=>{if(active){setSamples(x.slice(0,4));setSample(x[0]?.sample_id||'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  const identity=JSON.stringify([sample,anchor,unit,input,output]),value=data?.identity===identity?data:null;
  async function query(){try{const x=await get('/scalar-parameters?'+new URLSearchParams({sample,anchor,unit,input_coordinate:input,output_coordinate:output}));setData({...x,identity});setError('');}catch(e){setData(null);setError(e.message);}}
  return <section><h2>真实单参数、坐标与 MLP 单元</h2><p>选择任意原生编号；下方保留全部输入坐标贡献与全部单元写入。重算归一化输入和 FP64 求和，与原生 BF16 舍入分开记录。这不是“一个神经元就是一个概念”的证据。</p><div className="prefix-controls"><label>完整因子样本<select value={sample} onChange={e=>setSample(e.target.value)}>{samples.map(r=><option key={r.sample_id}>{r.sample_id}</option>)}</select></label><label>锚点<input type="number" min="0" max="1" value={anchor} onChange={e=>setAnchor(Number(e.target.value))}/></label>{[['输入坐标 i',input,setInput,2559],['MLP 单元 k',unit,setUnit,9727],['输出坐标 j',output,setOutput,2559]].map(([label,x,set,max])=><label key={label}>{label}<input type="number" min="0" max={max} value={x} onChange={e=>set(Number(e.target.value))}/></label>)}<button onClick={query} disabled={!sample}>核对真实参数链</button></div>{error&&<p role="alert">{error}</p>}{value&&<><pre>{JSON.stringify({scalar:value.scalar_chain,completeGateUpSums:value.all_input_coordinate_sums,completeUnitSum:value.all_unit_output_sum,nativeBF16Output:value.actual_output_coordinate},null,2)}</pre><Field data={value.input_terms}/><Field data={value.unit_terms}/></>}</section>;
}

function DiagnosticViewer({summary}){
  const [index,setIndex]=useState([]),[selected,setSelected]=useState(0),[data,setData]=useState(null),[error,setError]=useState('');const item=index[selected],identity=JSON.stringify(item),value=data?.identity===identity?data:null;
  async function refresh(){try{setIndex(await get('/analysis-index'));setSelected(0);setData(null);setError('');}catch(e){setError(e.message);}}
  async function query(){try{setData({...await get('/analysis-field?'+new URLSearchParams(item)),identity});setError('');}catch(e){setData(null);setError(e.message);}}
  return <section><h2>边界、幅值、概率误差与学得更新系统</h2><p>后续探索复用已看过的材料，不是新的盲测。首位置共享平均更新比仿射拟合更准确，尚不能解释成语义齿轮。概率归因覆盖所有原生坐标；谱数组的列是特征值编号，不是HiddenState坐标。谱分析属于学得的近似更新器，不属于原始 LLM 的谱或秩。</p><div className="prefix-controls"><button onClick={refresh}>刷新已完成诊断数组</button><label>完整数组<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{index.map((r,i)=><option key={JSON.stringify(r)} value={i}>{r.area} / {r.array} · {r.shape.join('×')}</option>)}</select></label><button disabled={!item} onClick={query}>读取完整数组</button></div>{error&&<p role="alert">{error}</p>}<Field data={value}/>{['native_source_audit','boundary_compilation','constant_boundary_control','boundary_relations','source_normalization','output_geometry','surrogate_stability','stable_trajectory','energy_audit','continuation'].map(k=><details key={k}><summary>{k}</summary><pre>{JSON.stringify(summary?.[k]||{},null,2)}</pre></details>)}</section>;
}

export default function RdcRelationStudy(){
  const [summary,setSummary]=useState(null),[error,setError]=useState(''),[scope,setScope]=useState('fresh'),[samples,setSamples]=useState([]),[loadedScope,setLoadedScope]=useState(''),[sample,setSample]=useState(''),[language,setLanguage]=useState('all');
  const [mode,setMode]=useState('field'),[layer,setLayer]=useState('h12'),[normalized,setNormalized]=useState(false),[anchor,setAnchor]=useState(0),[kind,setKind]=useState('current'),[genfield,setGenfield]=useState('self_predicted_h36');
  const [start,setStart]=useState(0),[count,setCount]=useState(2560),[data,setData]=useState(null),[detail,setDetail]=useState(null),[generation,setGeneration]=useState(null);
  const [relation,setRelation]=useState('nmod'),[control,setControl]=useState('distance_pos'),[pair,setPair]=useState('H12_H23'),[split,setSplit]=useState('test'),[matrixView,setMatrixView]=useState('train_z'),[matrixRow,setMatrixRow]=useState(0),[matrixCol,setMatrixCol]=useState(0),[matrix,setMatrix]=useState(null);
  const selected=samples.find(r=>r.sample_id===sample);const key=JSON.stringify([scope,sample,mode,layer,normalized,anchor,kind,genfield,start,count]);
  useEffect(()=>{let active=true;get('/overview').then(x=>{if(active)setSummary(x);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;get('/samples?scope='+scope).then(x=>{if(active){setSamples(x);setSample(x[0]?.sample_id||'');setLoadedScope(scope);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scope]);
  useEffect(()=>{if(!sample||loadedScope!==scope||!selected)return;let active=true;const p=selected.positions[anchor*3];get('/sample?'+new URLSearchParams({scope,sample,position:p})).then(x=>{if(active)setDetail({...x,identity:scope+sample+anchor});}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scope,sample,loadedScope,anchor,selected]);
  useEffect(()=>{if(!sample||loadedScope!==scope||mode==='matrix')return;let active=true;let url;
    if(mode==='field')url='/field?'+new URLSearchParams({scope,sample,layer,normalized,start,count});
    else if(mode==='prediction')url='/prediction?'+new URLSearchParams({scope,sample,kind,anchor,start,count});
    else if(mode==='units')url='/units?'+new URLSearchParams({start,count});
    else url='/generation?'+new URLSearchParams({sample,field:genfield,start,count});
    get(url).then(x=>{if(active){setData({...(mode==='generation'?x.field:x),key});setGeneration(mode==='generation'?{record:x.record,key}:null);setError('');}}).catch(e=>{if(active){setError(e.message);setData(null);}});return()=>{active=false;};
  },[scope,sample,loadedScope,mode,layer,normalized,anchor,kind,genfield,start,count,key]);
  const current=data?.key===key?data:null;const currentDetail=detail?.identity===scope+sample+anchor?detail:null;const visible=samples.filter(r=>(language==='all'||r.language===language)&&(mode!=='generation'||r.generated));
  const matrixKey=JSON.stringify([relation,control,pair,split,matrixView,matrixRow,matrixCol]);
  async function queryMatrix(){try{const x=await get('/matrix?'+new URLSearchParams({relation,control,pair,split,view:matrixView,row_start:matrixRow,column_start:matrixCol,count:64}));setMatrix({...x,key:matrixKey});setError('');}catch(e){setMatrix(null);setError(e.message);}}
  function switchMode(next){setMode(next);setStart(0);setCount(next==='units'?9728:2560);if(next==='generation'){setScope('fresh');const candidate=samples.find(r=>r.generated);if(scope==='fresh'&&candidate)setSample(candidate.sample_id);}if(next==='prediction'&&scope==='main'){const candidate=samples.find(r=>r.split==='test');if(candidate)setSample(candidate.sample_id);}}
  return <main className="prefix-app relation-app"><header><div><small>RDC · NATURAL RELATION DYNAMICS · PHASE 2715–2718</small><h1>自然前缀 · 关系与状态更新</h1><p>全坐标观察、严格对照、真实参数接续和连续生成。</p></div><nav><a href="/rdc-prefix">2711–2714前缀图谱</a><a href="/rdc">既有3D与机制路径</a><a href="/">研究主页</a></nav></header>
    <section className="prefix-warning"><strong>当前状态：结构拼图，尚未闭合</strong><p>512主库来源 + 128冻结后确认来源；H12/H23保留每个token、每个坐标。H24/H36/postnorm保留六位置。关系外积不是因果连线；自喂状态与每步提供真实状态严格分开。</p><p>自喂完整16-token续写相同：{summary?.generation?.full_continuation_exact_count??'—'}/64。自喂重复三元组比例：{fmt(summary?.generation?.self_repeated_trigram_fraction)}。</p><button onClick={()=>get('/overview').then(setSummary).catch(e=>setError(e.message))}>刷新已完成结果</button></section>
    <section><nav className="prefix-tabs">{[['field','全部token坐标场'],['matrix','全跨坐标关系矩阵'],['prediction','预测与原生block'],['units','全部MLP单元'],['generation','自然与自喂生成']].map(([id,label])=><button className={mode===id?'active':''} key={id} onClick={()=>switchMode(id)}>{label}</button>)}</nav>
      {mode!=='matrix'&&mode!=='units'&&<div className="prefix-controls"><label>材料集<select value={scope} disabled={mode==='generation'} onChange={e=>{setScope(e.target.value);setLanguage('all');}}><option value="fresh">冻结后确认128来源</option><option value="main">主库512来源</option></select></label><label>语言<select value={language} onChange={e=>{const value=e.target.value;setLanguage(value);const r=samples.find(r=>(value==='all'||r.language===value)&&(mode!=='generation'||r.generated));if(r)setSample(r.sample_id);}}>{['all','en','zh'].map(x=><option key={x}>{x}</option>)}</select></label><label className="prefix-wide">来源记录<select value={sample} onChange={e=>setSample(e.target.value)}>{visible.map(r=><option key={r.sample_id} value={r.sample_id}>{r.sample_id} · {r.split} · {r.genre} · {r.text.slice(0,60)}</option>)}</select></label><label>锚点<select value={anchor} onChange={e=>setAnchor(Number(e.target.value))}><option value="0">第一个</option><option value="1">第二个</option></select></label></div>}
      {mode==='field'&&<div className="prefix-controls"><label>采集层<select value={layer} onChange={e=>{setLayer(e.target.value);if(!['h12','h23'].includes(e.target.value))setNormalized(false);}}>{['h12','h23','h24','h36','postnorm'].map(x=><option key={x}>{x}</option>)}</select></label><label>数值规范化<select value={String(normalized)} disabled={!['h12','h23'].includes(layer)} onChange={e=>setNormalized(e.target.value==='true')}><option value="false">原始值</option><option value="true">冻结训练全token z-score</option></select></label></div>}
      {mode==='prediction'&&<div className="prefix-controls"><label>预测输入范围<select value={kind} onChange={e=>setKind(e.target.value)}><option value="current">真实H12 → 预测H36</option><option value="temporal">上一真实H36 + 已知新embedding</option><option value="native_all_sources">全部来源预测H23 → 真实block23</option><option value="native_hybrid">额外真实历史 + 当前预测H23</option><option value="boundary_affine">探索：首来源仿射边界，其余冻结二次规则</option></select></label></div>}
      {mode==='generation'&&<label>生成状态数组<select value={genfield} onChange={e=>setGenfield(e.target.value)}>{['native_h12','native_h36','self_predicted_h36','native_h36_on_self_prefix'].map(x=><option key={x}>{x}</option>)}</select></label>}
      {mode!=='matrix'&&<div className="prefix-controls"><label>起始原生编号<input type="number" min="0" max={mode==='units'?9727:2559} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>列数<input type="number" min="1" max={mode==='units'?9728:2560} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><button onClick={()=>{setStart(0);setCount(mode==='units'?9728:2560);}}>恢复全坐标 / 全单元</button></div>}
      {mode==='matrix'&&<><p>每个矩阵2560×2560项；这里按全部匹配来源精确重算64×64切片。noninitial是剔除首token端点的事后条件分析，仍保留每个原生坐标。无匹配时不回退到宽松对照。距离和图形不代表原生物理连接。</p><div className="prefix-controls"><label>关系<select value={relation} onChange={e=>setRelation(e.target.value)}>{relations.map(x=><option key={x}>{x}</option>)}</select></label><label>对照<select value={control} onChange={e=>setControl(e.target.value)}>{['distance','distance_pos','distance_pos_same_dependent_id','distance_pos_noninitial'].map(x=><option key={x}>{x}</option>)}</select></label><label>层对<select value={pair} onChange={e=>setPair(e.target.value)}>{['H12_H12','H12_H23','H23_H23'].map(x=><option key={x}>{x}</option>)}</select></label><label>划分<select value={split} onChange={e=>setSplit(e.target.value)}><option>train</option><option>test</option></select></label><label>矩阵值<select value={matrixView} onChange={e=>setMatrixView(e.target.value)}><option>train_z</option><option>raw</option></select></label><label>起始行<input type="number" min="0" max="2559" value={matrixRow} onChange={e=>setMatrixRow(Number(e.target.value))}/></label><label>起始列<input type="number" min="0" max="2559" value={matrixCol} onChange={e=>setMatrixCol(Number(e.target.value))}/></label><button onClick={queryMatrix}>重算矩阵切片</button></div><Field data={matrix?.key===matrixKey?matrix:null}/>{matrix?.key===matrixKey&&<><p>匹配来源{matrix.sources}；全矩阵训练/测试余弦{fmt(matrix.statistics?.all_coordinate_train_test_cosine)}。</p><details><summary>完整统计与来源投影区间</summary><pre>{JSON.stringify(matrix.statistics,null,2)}</pre></details></>}<a href={API+'/matrix-recipe'}>下载全部关系与对照索引（noninitial另按公开边界条件过滤）</a></>}
      {error&&<p className="prefix-error" role="alert">{error}</p>}{mode!=='matrix'&&<Field data={current}/>} {current?.available_inputs&&<p>{current.available_inputs} · MSE {fmt(current.MSE)}</p>}
      {mode!=='matrix'&&mode!=='units'&&mode!=='generation'&&currentDetail&&<details><summary>已知前缀、候选关系与原始身份</summary><blockquote>{currentDetail.prefix_graph.observed_prefix}</blockquote><p>{currentDetail.prefix_graph.status}</p><pre>{JSON.stringify(currentDetail.prefix_graph,null,2)}</pre><details><summary>事后原文与金标依存（不是预测输入）</summary><p>{currentDetail.text}</p><pre>{JSON.stringify(currentDetail.retrospective_ud,null,2)}</pre></details></details>}
      {mode==='generation'&&generation?.key===key&&<div className="relation-transcripts"><h2>同一起点，两条独立续写分支</h2><p>{generation.record.initial_prefix_text}</p><div><article><h3>原生贪心续写</h3><blockquote>{generation.record.native_text}</blockquote><p>{generation.record.native_stop}</p></article><article><h3>自喂状态续写</h3><blockquote>{generation.record.self_text}</blockquote><p>{generation.record.self_stop} · 第{generation.record.first_token_divergence_zero_based===null?'—':generation.record.first_token_divergence_zero_based+1}个token首次分叉</p></article></div><p>自喂分支在初始化后不再接收真实HiddenState。它的状态误差只与同一条自喂前缀上独立运行的原模型比较；低KL可能伴随重复。</p><details><summary>每一步完整指标与token IDs</summary><pre>{JSON.stringify(generation.record,null,2)}</pre></details></div>}
    </section><Metrics summary={summary}/><ScaleViewer/><ScalarViewer/><DiagnosticViewer summary={summary}/>
    <section><h2>真实计算与顺序尺度检查</h2><details open><summary>整个block23：全部预测来源 / 额外真实历史 / 算术核对</summary><pre>{JSON.stringify(summary?.native,null,2)}</pre></details><details><summary>三个模型、相同来源、各自原生坐标</summary><pre>{JSON.stringify(summary?.scale,null,2)}</pre></details><details><summary>外部关系器与词距、词性基线</summary><pre>{JSON.stringify(summary?.parser,null,2)}</pre></details></section>
    {!!summary?.figures?.length&&<section><h2>完整坐标科学图</h2>{summary.figures.map(f=><figure key={f.id}><figcaption>{f.title} · {f.note}</figcaption><a href={API+'/figure/'+f.id}><img src={API+'/figure/'+f.id} loading="lazy" alt={f.title}/></a></figure>)}</section>}
    <section><h2>证据边界与审查</h2><details><summary>附件保留项与过度结论修正</summary><pre>{JSON.stringify(summary?.review,null,2)}</pre></details><details><summary>整体方案、采集覆盖与材料限制</summary><pre>{JSON.stringify({plan:summary?.plan,material:summary?.material,capture:summary?.capture},null,2)}</pre></details><p>RDC名称保留；未形成新整体闭合定理。自然统计、拟合预测和真实参数恒等计算分别记账，不能直接推广为人脑机制或AGI证明。</p></section>
  </main>;
}
