"""Phase1270/C018-WP01: answer-excluded upstream causal recomputation.

The registered analysis supports never patch the answer position.  A switch in
the final answer therefore has to be generated by subsequent Transformer
blocks.  Three controls separate an inert causally prior prefix, direct answer
state replay, and an algebraically complete with-answer suffix.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import math
import os
import platform
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import torch


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tests/glm5"))
import phase1266_c014_free_transformer_population_certificate as p1266
import phase1268_c016_distributed_causal_support_ladder as p1268
import phase1269_c017_causal_support_funnel_confirmation as p1269


PHASE = 1270
CAMPAIGN = "C018"
CONTRACT_ID = "EXP-C018-WP01-001"
OUT = ROOT / "tests/glm5/result/phase1270_c018_answer_excluded_causal_recomputation"
PROTOCOL = OUT / "protocol/preregistration.json"
ENVIRONMENT = OUT / "protocol/environment_snapshot.json"
MATERIAL = OUT / "material/frozen_recomputation_worlds.jsonl"
PREAUDIT = OUT / "audit/independent_preaudit.json"
QUALIFICATION = OUT / "raw/behavior_qualification.jsonl"
MODELS = OUT / "raw/model_results.jsonl"
SUMMARY = OUT / "raw/run_summary.json"
COMPLETE = OUT / "raw/FORMAL_RUN_COMPLETE.json"
FINAL = OUT / "analysis/final.json"
FINAL_AUDIT = OUT / "audit/independent_final_audit.json"
AUDITOR = ROOT / "tests/glm5/phase1270_c018_answer_excluded_causal_recomputation_audit.py"
CONTRACT = ROOT / "research/ai2050_research_os/contracts/EXP-C018-WP01-001.json"
PHASE1269_FINAL = ROOT / "tests/glm5/result/phase1269_c017_causal_support_funnel_confirmation/analysis/final.json"
PHASE1269_AUDIT = ROOT / "tests/glm5/result/phase1269_c017_causal_support_funnel_confirmation/audit/independent_final_audit.json"
PHASE1269_COMPLETE = ROOT / "tests/glm5/result/phase1269_c017_causal_support_funnel_confirmation/raw/FORMAL_RUN_COMPLETE.json"

ARCHITECTURES = p1266.ARCHITECTURES
SEED_POOLS = {
    "shallow4": [1_270_401_001, 1_270_401_101, 1_270_401_201, 1_270_401_301, 1_270_401_401],
    "middle6": [1_270_601_001, 1_270_601_101, 1_270_601_201, 1_270_601_301, 1_270_601_401],
    "deep8": [1_270_801_001, 1_270_801_101, 1_270_801_201, 1_270_801_301, 1_270_801_401],
}
SELECT_PER_DEPTH = 3
MATERIAL_SEEDS = {"qualification": 1_270_910_001, "confirmation": 1_270_930_001}
PARTITION_COUNTS = {"qualification": 1024, "oracle": 3456, "confirmation": 1024}
ANALYSIS_FAMILIES = (
    "source_only",
    "source_query_no_answer",
    "source_map_query_no_answer",
    "semantic_chain_no_answer",
    "causal_prefix_no_answer",
)
SUPPORT_SIZES = {
    "source_only": 1,
    "source_query_no_answer": 3,
    "source_map_query_no_answer": 5,
    "semantic_chain_no_answer": 6,
    "causal_prefix_no_answer": 18,
}
CONTROL_FAMILIES = ("pre_source_prefix", "answer_only", "causal_suffix_with_answer")
FAMILIES = ANALYSIS_FAMILIES + CONTROL_FAMILIES
SELECTION_DRAWS = 32768
GLOBAL_ERROR_BUDGET = 0.01
PASS_MIN = 0.95
NULL_MAX = 0.05
POSITIVE_MIN = 0.999
ROBUST_MULTIPLIER = 2.0
MAX_MODELS = len(ARCHITECTURES) * SELECT_PER_DEPTH
MAX_EVENTS = sum(config.layers for config in ARCHITECTURES.values()) * SELECT_PER_DEPTH
CERTIFICATE_RADIUS = math.sqrt(
    math.log(2.0 * MAX_EVENTS * len(FAMILIES) * 2.0 / GLOBAL_ERROR_BUDGET)
    / (2.0 * SELECTION_DRAWS)
)
THRESHOLDS = {
    "behavior_accuracy_min": 0.995,
    "executor_gap_max": 2.0e-4,
    "support_accuracy_min": PASS_MIN,
    "certificate_radius": CERTIFICATE_RADIUS,
    "false_authorizations_max": 0,
    "robust_coverage_min": 0.90,
    "confirmation_accuracy_min": 0.95,
    "null_switch_accuracy_max": NULL_MAX,
    "positive_control_accuracy_min": POSITIVE_MIN,
    "answer_free_recompute_models_min": 6,
    "answer_free_recompute_per_depth_min": 2,
    "sparse_recompute_models_min": 6,
    "sparse_recompute_per_depth_min": 2,
    "selected_models_required": 9,
}


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def digest(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(canonical_json(row) + "\n")
    os.replace(temporary, path)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def sample_worlds(partition: str, count: int, seed: int) -> list[dict[str, Any]]:
    return p1269.sample_worlds(partition, count, seed)


def make_material() -> list[dict[str, Any]]:
    rows = sample_worlds("qualification", PARTITION_COUNTS["qualification"], MATERIAL_SEEDS["qualification"])
    rows.extend(p1266.enumerate_oracle_worlds())
    rows.extend(sample_worlds("confirmation", PARTITION_COUNTS["confirmation"], MATERIAL_SEEDS["confirmation"]))
    return rows


def protocol_payload(rows: list[dict[str, Any]]) -> dict[str, Any]:
    predecessor = read_json(PHASE1269_FINAL)
    audit = read_json(PHASE1269_AUDIT)
    timeless = {
        "phase": PHASE,
        "campaign": CAMPAIGN,
        "contract_id": CONTRACT_ID,
        "schema_version": "phase1270.c018.answer_excluded_recomputation.v1",
        "claim_type": "free_transformer_answer_excluded_upstream_recomputation",
        "question": "Can upstream donor states switch the answer through later Transformer blocks when answer position 22 is never patched?",
        "phase1269_dependency": {
            "formal_complete": PHASE1269_COMPLETE.exists(),
            "decision": predecessor.get("decision"),
            "passed": predecessor.get("passed"),
            "final_hash": file_sha256(PHASE1269_FINAL),
            "audit_passed": audit.get("all_checks_passed"),
            "audit_hash": file_sha256(PHASE1269_AUDIT),
        },
        "architectures": {name: vars(config) for name, config in ARCHITECTURES.items()},
        "seed_pools": SEED_POOLS,
        "behavior_selection": {
            "rule": "first three behavior-qualified seeds per depth; hidden states are never read for rejected seeds",
            "select_per_depth": SELECT_PER_DEPTH,
            "partition": "qualification",
        },
        "partitions": PARTITION_COUNTS,
        "material_seeds": MATERIAL_SEEDS,
        "world_digest": digest([{"row_id": row["row_id"], "partition": row["partition"], "row_digest": row["row_digest"]} for row in rows]),
        "analysis_families": list(ANALYSIS_FAMILIES),
        "support_sizes": SUPPORT_SIZES,
        "control_families": list(CONTROL_FAMILIES),
        "answer_position": 22,
        "selection": {
            "draws": SELECTION_DRAWS,
            "radius": CERTIFICATE_RADIUS,
            "rule": "first answer-free family whose forward and reverse lower bounds are at least 0.95",
        },
        "model_decisions": {
            "answer_free_recompute": "at least one independently confirmed selected answer-free family at a nonterminal layer and all controls pass",
            "sparse_recompute": "answer_free_recompute with at least one independently confirmed selected support of size at most 6",
        },
        "thresholds": THRESHOLDS,
        "budgets": {"max_formal_runs": 1, "max_adaptive_rounds": 0, "max_gpu_hours": 3.5},
        "hard_stops": [
            "No analysis mask includes answer position 22.",
            "Behavior screening cannot inspect hidden states or mechanism outcomes.",
            "Exact oracle population scores cannot select support or layer.",
            "Confirmation cannot select support, layer, threshold, or seed.",
            "The terminal layer must reject answer-free switching while direct answer replay passes.",
            "No donor compiler or pretrained model is run automatically.",
        ],
        "structured_scope": {
            "task": "synthetic cyclic-code",
            "population": "behavior-qualified small free same-executor Transformers",
            "intervention": "exact same-case residual-state replacement excluding answer position",
            "natural_language": False,
            "pretrained": False,
        },
        "source_hashes": {
            "main": file_sha256(Path(__file__).resolve()),
            "auditor": file_sha256(AUDITOR),
            "contract": file_sha256(CONTRACT),
            "phase1269": file_sha256(ROOT / "tests/glm5/phase1269_c017_causal_support_funnel_confirmation.py"),
            "executor": file_sha256(ROOT / "tests/glm5/phase1268_c016_distributed_causal_support_ladder.py"),
            "task": file_sha256(ROOT / "tests/glm5/phase1251_c004_causal_slice_competition.py"),
        },
    }
    return {**timeless, "created_at_utc": utc_now(), "protocol_digest": digest(timeless)}


def environment_snapshot() -> dict[str, Any]:
    return {
        "created_at_utc": utc_now(),
        "python": sys.version,
        "platform": platform.platform(),
        "torch": torch.__version__,
        "cuda_available": torch.cuda.is_available(),
        "cuda_version": torch.version.cuda,
        "device_name": torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
        "precision": "fp32 training/intervention; fp64 audit arithmetic",
    }


def preregister(force: bool) -> None:
    if PROTOCOL.exists() and not force:
        raise RuntimeError("protocol already exists")
    predecessor = read_json(PHASE1269_FINAL)
    audit = read_json(PHASE1269_AUDIT)
    if predecessor.get("decision") != "causal_support_funnel_confirmed" or predecessor.get("passed") is not True:
        raise RuntimeError("Phase1269 did not authorize C018 design")
    if audit.get("all_checks_passed") is not True or not PHASE1269_COMPLETE.exists():
        raise RuntimeError("Phase1269 audit dependency failed")
    if not AUDITOR.exists() or not CONTRACT.exists():
        raise RuntimeError("auditor and contract must exist")
    rows = make_material()
    write_jsonl(MATERIAL, rows)
    atomic_json(ENVIRONMENT, environment_snapshot())
    atomic_json(PROTOCOL, protocol_payload(rows))
    print(canonical_json({"status": "preregistered", "rows": len(rows), "seed_pool": sum(map(len, SEED_POOLS.values())), "radius": CERTIFICATE_RADIUS}))


def verify_protocol() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    protocol = read_json(PROTOCOL)
    rows = read_jsonl(MATERIAL)
    expected = protocol_payload(rows)
    if protocol["protocol_digest"] != expected["protocol_digest"]:
        raise RuntimeError("protocol digest drift")
    if protocol["source_hashes"] != expected["source_hashes"] or protocol["thresholds"] != THRESHOLDS:
        raise RuntimeError("source or threshold drift")
    counts = {name: sum(row["partition"] == name for row in rows) for name in PARTITION_COUNTS}
    if counts != PARTITION_COUNTS:
        raise RuntimeError(f"partition drift: {counts}")
    return protocol, rows


def partition_rows(rows: list[dict[str, Any]], partition: str) -> list[dict[str, Any]]:
    return [row for row in rows if row["partition"] == partition]


def support_mask(rows: list[dict[str, Any]], family: str, device: torch.device) -> torch.Tensor:
    mask = torch.zeros((len(rows), 23), dtype=torch.bool, device=device)
    fixed = {
        "source_only": (4,),
        "source_query_no_answer": (4, 20, 21),
        "pre_source_prefix": (0, 1, 2, 3),
        "answer_only": (22,),
    }
    if family in fixed:
        mask[:, list(fixed[family])] = True
        return mask
    if family in ("source_map_query_no_answer", "semantic_chain_no_answer"):
        mask[:, [4, 20, 21]] = True
        if family == "semantic_chain_no_answer":
            mask[:, 11] = True
        for index, row in enumerate(rows):
            pair = 12 + 2 * row["codebook_order"].index(row["target_code"])
            mask[index, pair] = True
            mask[index, pair + 1] = True
        return mask
    if family == "causal_prefix_no_answer":
        mask[:, 4:22] = True
        return mask
    if family == "causal_suffix_with_answer":
        mask[:, 4:23] = True
        return mask
    raise ValueError(family)


def evaluate_supports(
    model,
    rows: list[dict[str, Any]],
    pairs: list[tuple[int, str]],
    device: torch.device,
    batch_size: int = 512,
) -> dict[str, dict[str, list[bool]]]:
    outcomes = {f"{layer}:{family}": {"patch": [], "reverse": []} for layer, family in pairs}
    with torch.inference_mode():
        for start in range(0, len(rows), batch_size):
            batch = rows[start : start + batch_size]
            h01_ids = torch.tensor([row["h01_ids"] for row in batch], device=device)
            h11_ids = torch.tensor([row["h11_ids"] for row in batch], device=device)
            _logits01, trace01 = p1268.full_residual_forward(model, h01_ids, capture=True)
            _logits11, trace11 = p1268.full_residual_forward(model, h11_ids, capture=True)
            assert trace01 is not None and trace11 is not None
            target = torch.tensor([row["answers"]["h11"] for row in batch], device=device)
            base = torch.tensor([row["answers"]["h01"] for row in batch], device=device)
            masks = {family: support_mask(batch, family, device) for _layer, family in pairs}
            for layer, family in pairs:
                mask = masks[family]
                patch_logits, _ = p1268.full_residual_forward(
                    model,
                    h01_ids,
                    actions={layer: p1268.patch_action(trace11[:, layer], mask)},
                )
                reverse_logits, _ = p1268.full_residual_forward(
                    model,
                    h11_ids,
                    actions={layer: p1268.patch_action(trace01[:, layer], mask)},
                )
                patch_pred = torch.argmax(patch_logits[:, -1, p1266.CANDIDATE_SLICE], dim=-1)
                reverse_pred = torch.argmax(reverse_logits[:, -1, p1266.CANDIDATE_SLICE], dim=-1)
                key = f"{layer}:{family}"
                outcomes[key]["patch"].extend((patch_pred == target).cpu().tolist())
                outcomes[key]["reverse"].extend((reverse_pred == base).cpu().tolist())
    return outcomes


def selection_indices(seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed + 7_777_270)
    return rng.integers(0, PARTITION_COUNTS["oracle"], size=SELECTION_DRAWS)


def bounds(point: float) -> dict[str, float]:
    return {"point": point, "lower": max(0.0, point - CERTIFICATE_RADIUS), "upper": min(1.0, point + CERTIFICATE_RADIUS)}


def qualify_model(model, training: dict[str, Any], rows: list[dict[str, Any]], device: torch.device) -> dict[str, Any]:
    natural_accuracy, executor_gap = p1268.evaluate_behavior(model, rows, device)
    passed = (
        min(training["accuracy_overall"], training["accuracy_direct"], training["accuracy_code"], natural_accuracy)
        >= THRESHOLDS["behavior_accuracy_min"]
        and executor_gap <= THRESHOLDS["executor_gap_max"]
    )
    return {"training": training, "qualification_accuracy": natural_accuracy, "executor_gap": executor_gap, "passed": passed}


def measure_selected_model(
    model,
    architecture: str,
    seed: int,
    pool_index: int,
    selected_index: int,
    qualification: dict[str, Any],
    rows: list[dict[str, Any]],
    device: torch.device,
) -> dict[str, Any]:
    config = ARCHITECTURES[architecture]
    oracle_rows = partition_rows(rows, "oracle")
    confirmation_rows = partition_rows(rows, "confirmation")
    pairs = [(layer, family) for layer in range(config.layers) for family in FAMILIES]
    oracle = evaluate_supports(model, oracle_rows, pairs, device)
    selected_indices = selection_indices(seed)
    event_ledger: list[dict[str, Any]] = []
    trajectory: list[tuple[int, str]] = []
    for layer in range(config.layers):
        first = None
        for family in FAMILIES:
            outcome = oracle[f"{layer}:{family}"]
            patch = np.asarray(outcome["patch"], dtype=np.float64)
            reverse = np.asarray(outcome["reverse"], dtype=np.float64)
            population_patch, population_reverse = float(patch.mean()), float(reverse.mean())
            sample_patch, sample_reverse = float(patch[selected_indices].mean()), float(reverse[selected_indices].mean())
            patch_bounds, reverse_bounds = bounds(sample_patch), bounds(sample_reverse)
            population_score = min(population_patch, population_reverse)
            exact_pass = population_score >= PASS_MIN
            certificate_pass = min(patch_bounds["lower"], reverse_bounds["lower"]) >= PASS_MIN
            robust = population_score >= PASS_MIN + ROBUST_MULTIPLIER * CERTIFICATE_RADIUS
            selected = family in ANALYSIS_FAMILIES and first is None and certificate_pass
            if selected:
                first = family
            event_ledger.append(
                {
                    "layer": layer,
                    "family": family,
                    "population_patch_accuracy": population_patch,
                    "population_reverse_accuracy": population_reverse,
                    "population_score": population_score,
                    "sample_patch_accuracy": sample_patch,
                    "sample_reverse_accuracy": sample_reverse,
                    "patch_bounds": patch_bounds,
                    "reverse_bounds": reverse_bounds,
                    "exact_pass": exact_pass,
                    "certificate_pass": certificate_pass,
                    "robust_actionable": robust,
                    "selected": selected,
                }
            )
        trajectory.append((layer, first or "abstain"))
    confirmation_raw = evaluate_supports(model, confirmation_rows, pairs, device)
    confirmation_ledger: list[dict[str, Any]] = []
    confirmation_map: dict[tuple[int, str], dict[str, Any]] = {}
    for layer, family in pairs:
        outcome = confirmation_raw[f"{layer}:{family}"]
        patch_accuracy = float(np.mean(outcome["patch"]))
        reverse_accuracy = float(np.mean(outcome["reverse"]))
        item = {
            "layer": layer,
            "family": family,
            "cases": len(confirmation_rows),
            "patch_accuracy": patch_accuracy,
            "reverse_accuracy": reverse_accuracy,
            "support_passed": min(patch_accuracy, reverse_accuracy) >= THRESHOLDS["confirmation_accuracy_min"],
        }
        confirmation_ledger.append(item)
        confirmation_map[(layer, family)] = item
    confirmed_selected = []
    for layer, family in trajectory:
        passed = family != "abstain" and confirmation_map[(layer, family)]["support_passed"]
        confirmed_selected.append({"layer": layer, "family": family, "passed": passed})
    nonterminal = config.layers - 1
    recompute_layers = [item["layer"] for item in confirmed_selected if item["layer"] < nonterminal and item["passed"]]
    sparse_layers = [
        item["layer"]
        for item in confirmed_selected
        if item["layer"] < nonterminal
        and item["passed"]
        and SUPPORT_SIZES.get(item["family"], 10_000) <= 6
    ]
    null_controls = [confirmation_map[(layer, "pre_source_prefix")] for layer in range(config.layers)]
    suffix_controls = [confirmation_map[(layer, "causal_suffix_with_answer")] for layer in range(config.layers)]
    final_no_answer = confirmation_map[(nonterminal, "causal_prefix_no_answer")]
    final_answer = confirmation_map[(nonterminal, "answer_only")]
    null_pass = all(max(item["patch_accuracy"], item["reverse_accuracy"]) <= NULL_MAX for item in null_controls)
    suffix_pass = all(min(item["patch_accuracy"], item["reverse_accuracy"]) >= POSITIVE_MIN for item in suffix_controls)
    terminal_no_answer_pass = max(final_no_answer["patch_accuracy"], final_no_answer["reverse_accuracy"]) <= NULL_MAX
    terminal_answer_replay_pass = min(final_answer["patch_accuracy"], final_answer["reverse_accuracy"]) >= POSITIVE_MIN
    controls_passed = null_pass and suffix_pass and terminal_no_answer_pass and terminal_answer_replay_pass
    answer_free_recompute = bool(recompute_layers) and controls_passed
    sparse_recompute = bool(sparse_layers) and controls_passed
    last_layer = max(recompute_layers) if recompute_layers else None
    return {
        "model_key": f"{architecture}_s{selected_index}_p{pool_index}",
        "architecture": architecture,
        "seed": seed,
        "pool_index": pool_index,
        "selected_index": selected_index,
        "qualification": qualification,
        "event_ledger": event_ledger,
        "trajectory": [{"layer": layer, "family": family, "size": SUPPORT_SIZES.get(family)} for layer, family in trajectory],
        "confirmation_ledger": confirmation_ledger,
        "confirmed_selected": confirmed_selected,
        "recompute_layers": recompute_layers,
        "sparse_recompute_layers": sparse_layers,
        "last_recompute_layer": last_layer,
        "last_recompute_relative": last_layer / max(1, config.layers - 1) if last_layer is not None else None,
        "null_control_passed": null_pass,
        "with_answer_suffix_control_passed": suffix_pass,
        "terminal_no_answer_negative": terminal_no_answer_pass,
        "terminal_answer_replay_positive": terminal_answer_replay_pass,
        "controls_passed": controls_passed,
        "answer_free_recompute_passed": answer_free_recompute,
        "sparse_recompute_passed": sparse_recompute,
    }


def summarize(qualification: list[dict[str, Any]], rows: list[dict[str, Any]]) -> dict[str, Any]:
    all_events = [event for row in rows for event in row["event_ledger"]]
    false_authorizations = sum(event["certificate_pass"] and not event["exact_pass"] for event in all_events)
    robust_events = [event for event in all_events if event["robust_actionable"]]
    robust_coverage = sum(event["certificate_pass"] for event in robust_events) / max(1, len(robust_events))
    controls_models = [row for row in rows if row["controls_passed"]]
    recompute_models = [row for row in rows if row["answer_free_recompute_passed"]]
    sparse_models = [row for row in rows if row["sparse_recompute_passed"]]
    per_depth = {architecture: sum(row["architecture"] == architecture for row in recompute_models) for architecture in ARCHITECTURES}
    sparse_per_depth = {architecture: sum(row["architecture"] == architecture for row in sparse_models) for architecture in ARCHITECTURES}
    selected_per_depth = {architecture: sum(row["architecture"] == architecture for row in rows) for architecture in ARCHITECTURES}
    qualification_complete = len(rows) == THRESHOLDS["selected_models_required"] and all(value == SELECT_PER_DEPTH for value in selected_per_depth.values())
    recompute_breadth = len(recompute_models) >= THRESHOLDS["answer_free_recompute_models_min"] and all(value >= THRESHOLDS["answer_free_recompute_per_depth_min"] for value in per_depth.values())
    sparse_breadth = len(sparse_models) >= THRESHOLDS["sparse_recompute_models_min"] and all(value >= THRESHOLDS["sparse_recompute_per_depth_min"] for value in sparse_per_depth.values())
    gates = {
        "G-BEHAVIOR-SCREEN-COMPLETE": qualification_complete,
        "G-ZERO-FALSE-AUTHORIZATION": false_authorizations <= THRESHOLDS["false_authorizations_max"],
        "G-ROBUST-COVERAGE": bool(robust_events) and robust_coverage >= THRESHOLDS["robust_coverage_min"],
        "G-CONTROL-SUITE": len(controls_models) == len(rows) == THRESHOLDS["selected_models_required"],
        "G-ANSWER-FREE-RECOMPUTE-BREADTH": recompute_breadth,
        "G-NO-PRETRAINED": True,
    }
    last_relative = [row["last_recompute_relative"] for row in rows if row["last_recompute_relative"] is not None]
    passed = all(gates.values())
    return {
        "attempted_seeds": len(qualification),
        "selected_models": len(rows),
        "selected_per_depth": selected_per_depth,
        "events": len(all_events),
        "false_authorizations": false_authorizations,
        "robust_events": len(robust_events),
        "robust_coverage": robust_coverage,
        "control_models_passed": len(controls_models),
        "answer_free_recompute_models": len(recompute_models),
        "answer_free_recompute_per_depth": per_depth,
        "sparse_recompute_models": len(sparse_models),
        "sparse_recompute_per_depth": sparse_per_depth,
        "sparse_recompute_breadth_passed": sparse_breadth,
        "last_recompute_relative_median": float(np.median(last_relative)) if last_relative else None,
        "gates": gates,
        "decision": "answer_excluded_upstream_recomputation_confirmed" if passed else "answer_excluded_upstream_recomputation_not_confirmed",
        "passed": passed,
    }


def run(device_name: str) -> None:
    if COMPLETE.exists():
        raise RuntimeError("formal run already completed")
    if not PREAUDIT.exists() or not read_json(PREAUDIT).get("all_checks_passed"):
        raise RuntimeError("independent preaudit must pass")
    protocol, material = verify_protocol()
    if device_name != "cuda" or not torch.cuda.is_available():
        raise RuntimeError("formal run requires CUDA")
    device = torch.device("cuda")
    qualification_rows = partition_rows(material, "qualification")
    started = time.perf_counter()
    qualification_records: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    for architecture, config in ARCHITECTURES.items():
        selected = 0
        for pool_index, seed in enumerate(SEED_POOLS[architecture]):
            if selected >= SELECT_PER_DEPTH:
                break
            p1266.set_seed(seed)
            model, training = p1266.task_module.train_model(config, seed, device)
            qualification = qualify_model(model, training, qualification_rows, device)
            record = {
                "architecture": architecture,
                "pool_index": pool_index,
                "seed": seed,
                **qualification,
                "selected": qualification["passed"] and selected < SELECT_PER_DEPTH,
            }
            qualification_records.append(record)
            write_jsonl(QUALIFICATION, qualification_records)
            if record["selected"]:
                result = measure_selected_model(model, architecture, seed, pool_index, selected, qualification, material, device)
                results.append(result)
                selected += 1
                write_jsonl(MODELS, results)
                print(canonical_json({"architecture": architecture, "selected": selected, "seed": seed, "recompute": result["answer_free_recompute_passed"], "sparse": result["sparse_recompute_passed"], "trajectory": [item["family"] for item in result["trajectory"]]}), flush=True)
            else:
                print(canonical_json({"architecture": architecture, "rejected_pool_index": pool_index, "seed": seed, "qualification": qualification["qualification_accuracy"]}), flush=True)
            del model
            gc.collect()
            torch.cuda.empty_cache()
        if selected < SELECT_PER_DEPTH:
            print(canonical_json({"architecture": architecture, "selected_shortfall": SELECT_PER_DEPTH - selected}), flush=True)
    torch.cuda.synchronize()
    elapsed = time.perf_counter() - started
    write_jsonl(QUALIFICATION, qualification_records)
    write_jsonl(MODELS, results)
    run_summary = {
        "phase": PHASE,
        "contract_id": CONTRACT_ID,
        "created_at_utc": utc_now(),
        "attempted_seeds": len(qualification_records),
        "selected_models": len(results),
        "elapsed_seconds": elapsed,
        "gpu_hours": elapsed / 3600.0,
        "device": torch.cuda.get_device_name(0),
        "qualification_hash": file_sha256(QUALIFICATION),
        "models_hash": file_sha256(MODELS),
        "run_digest": digest({"qualification": qualification_records, "models": results}),
        "protocol_digest": protocol["protocol_digest"],
        "pretrained_model_loaded": False,
    }
    atomic_json(SUMMARY, run_summary)
    atomic_json(COMPLETE, {"status": "formal_run_complete", "created_at_utc": utc_now(), "run_digest": run_summary["run_digest"], "models_hash": run_summary["models_hash"]})


def analyze() -> None:
    if not COMPLETE.exists():
        raise RuntimeError("formal run incomplete")
    protocol, _material = verify_protocol()
    qualification = read_jsonl(QUALIFICATION)
    results = read_jsonl(MODELS)
    summary = summarize(qualification, results)
    final = {
        "phase": PHASE,
        "campaign": CAMPAIGN,
        "contract_id": CONTRACT_ID,
        "created_at_utc": utc_now(),
        **summary,
        "authorization": {
            "necessity_contract_design": summary["passed"],
            "independent_sparse_donor_design": summary["passed"] and summary["sparse_recompute_breadth_passed"],
            "automatic_pretrained_run": False,
            "qwen3": False,
            "glm4": False,
            "ds7b": False,
        },
        "structured_scope": protocol["structured_scope"],
        "protocol_digest": protocol["protocol_digest"],
        "qualification_hash": file_sha256(QUALIFICATION),
        "models_hash": file_sha256(MODELS),
        "run_digest": digest({"qualification": qualification, "models": results}),
    }
    final["final_digest"] = digest(final)
    atomic_json(FINAL, final)
    print(canonical_json({"decision": summary["decision"], "passed": summary["passed"], "recompute": summary["answer_free_recompute_models"], "sparse": summary["sparse_recompute_models"], "per_depth": summary["answer_free_recompute_per_depth"]}))


def run_auditor(mode: str) -> None:
    subprocess.run([sys.executable, str(AUDITOR), "--mode", mode], cwd=ROOT, check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    prereg = sub.add_parser("preregister")
    prereg.add_argument("--force", action="store_true")
    run_parser = sub.add_parser("run")
    run_parser.add_argument("--device", default="cuda")
    sub.add_parser("analyze")
    audit = sub.add_parser("audit")
    audit.add_argument("--mode", choices=("pre", "final"), required=True)
    args = parser.parse_args()
    if args.command == "preregister":
        preregister(args.force)
    elif args.command == "run":
        run(args.device)
    elif args.command == "analyze":
        analyze()
    elif args.command == "audit":
        run_auditor(args.mode)


if __name__ == "__main__":
    main()
