#!/usr/bin/env python3
"""Phase1403: freeze C065 active-only natural-state mechanism contract."""
from __future__ import annotations
import json,sys
from collections import Counter,defaultdict
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];TESTS=ROOT/"tests/glm5";sys.path.insert(0,str(TESTS));import phase1331_relational_measurement_core as core
PHASE,CAMPAIGN=1403,"C065";PARENT=TESTS/"result/phase1402_c064_behavior_gate_closure";C=TESTS/"result/phase1400_c064_fixed_answer_factorial_contract";B=TESTS/"result/phase1401_c064_behavior";OUT=TESTS/"result/phase1403_c065_active_only_natural_state_contract"

def main():
 if (OUT/"analysis/final.json").exists():raise RuntimeError("Phase1403 exists")
 parent=core.load(PARENT/"analysis/final.json");pa=core.load(PARENT/"audit/independent_final_audit.json");ba=core.load(B/"audit/independent_final_audit.json")
 if parent["authorization"]!="preregister_c065_active_only_natural_state_campaign" or not pa["all_checks_passed"] or not ba["all_checks_passed"]:raise RuntimeError("parent missing")
 p0=core.load(C/"protocol/preregistration.json");active={r["case_id"]:r for r in core.rows(B/"raw/active_behavior.jsonl")};factors=core.rows(C/"material/factor_sets.jsonl");keys=("recipient","surface_same","member_same","family_same_polarity","polarity_same_family","family_and_polarity")
 eligible=[r for r in factors if all(active[r[k]]["correct"] for k in keys)];cells=defaultdict(list)
 for r in eligible:cells[(r["family"],r["partition"],r["surface"])].append(r)
 qualified=[];selected=[];route={}
 for family in p0["material"]["families"]:
  values={(part,surface):cells[(family,part,surface)] for part in p0["material"]["partitions"] for surface in p0["material"]["surfaces"]};ok=all(len(v)>=2 for v in values.values());route[family]={"cell_counts":{f"{a}:{b}":len(v) for (a,b),v in values.items()},"qualified":ok}
  if ok:
   qualified.append(family)
   for key in sorted(values):selected.extend(sorted(values[key],key=lambda r:r["set_id"])[:2])
 checks={"parents":pa["all_checks_passed"] and ba["all_checks_passed"],"active_only_128":len(eligible)==128,"qualified_exact":qualified==["animal","profession","country"],"selected_54":len(selected)==54,"partition_balance":Counter(r["partition"] for r in selected)=={q:18 for q in p0["material"]["partitions"]},"family_balance":Counter(r["family"] for r in selected)=={q:18 for q in qualified},"surface_balance":Counter(r["surface"] for r in selected)=={q:18 for q in p0["material"]["surfaces"]},"all_selected_behavior_correct":all(all(active[r[k]]["correct"] for k in keys) for r in selected),"hidden_not_previously_accessed":True}
 if not all(checks.values()):raise RuntimeError({k:v for k,v in checks.items() if not v})
 core.write_rows(OUT/"material/eligible_factor_sets.jsonl",selected);core.save(OUT/"material/route_qualification.json",route)
 protocol={"phase":PHASE,"campaign":CAMPAIGN,"schema":"c065.active_only_natural_state.v1","model":"qwen3-bfloat16-cuda-no-quantization","research_object":"natural active relation state: family identity versus joint truth/output polarity","allowed_observables":["input token embeddings","all layers/all positions full-dimensional hidden states","logits"],"forbidden":["attention","MLP","parameter scan","gradient","PCA","t-SNE","UMAP","SAE","learned probe","post-reveal candidate or threshold change"],"material":{"source_contract":"C064 active-only behavior-qualified donor sets","qualified_families":qualified,"selected_count":54,"partition_count":18,"surface_count":18,"factor_sha256":core.sha(OUT/"material/eligible_factor_sets.jsonl"),"active_behavior_sha256":core.sha(B/"raw/active_behavior.jsonl"),"human_naturalness_lock":False},"camera":{"known_truth_systems":256,"qwen_cases":18,"logit_identity_max_abs_diff":1e-5,"all_state_identity_relative_l2_max":1e-6,"role_swap_exact":True,"multi_checkpoint_exact":True},"observation":{"partition":"response_discovery","all_hidden_state_indices":list(range(37)),"all_physical_positions":True,"same_surface_donors":["member_same","family_same_polarity","polarity_same_family","family_and_polarity"],"role_aligned_control":"surface_same","roles":["record_target","record_family","query_target","query_family","boundary"],"windows":[[1,15],[16,24],[25,36]],"objects":{"family_identity":"cosine_distance(family_same_polarity)-cosine_distance(member_same)","joint_polarity":"cosine_distance(polarity_same_family)-cosine_distance(member_same)"},"top_candidates_per_surface_object_window":1,"candidate_count_max":18,"candidate_source_is_discovery_only":True},"factorial_swap":{"partitions":["confirmation","lockbox"],"arms":["self","surface_same","member_same","family_same_polarity","polarity_same_family","family_and_polarity"],"self_max_abs_diff":1e-4,"surface_control_loss_fraction_max":0.25,"member_control_loss_fraction_max":0.50,"family_damage_median_min":0.5,"family_over_member_median_min":0.25,"family_over_member_win_min":0.65,"polarity_redirect_fraction_min":0.65,"minimum_family_breadth":2},"branching":{"phase1404":"camera","phase1405":"natural discovery field","phase1406":"holdout factorial swaps","phase1407":"closure"},"claim_boundary":{"allowed":"Qwen-specific controlled-registry natural whole-state family-versus-joint-polarity evidence","forbidden":["semantic neurons","truth/answer-token separation","minimal coordinates","unique natural path","attention/MLP/parameter mechanism","cross-model/open-language law"]},"stop_rule":"camera failure blocks hidden; candidate route failure eliminates only that route; all routes then close C065","created_at_utc":datetime.now(timezone.utc).isoformat()}
 protocol["contract_sha256"]=core.digest(protocol);protocol["authorization"]="run_phase1404_c065_state_swap_camera";core.save(OUT/"protocol/preregistration.json",protocol);core.save(OUT/"audit/pre_hidden_freeze.json",{"checks":checks,"passed":sum(checks.values()),"total":len(checks),"all_checks_passed":all(checks.values()),"route_qualification":route});core.save(OUT/"analysis/final.json",{"phase":PHASE,"campaign":CAMPAIGN,"all_gates_passed":True,"authorization":protocol["authorization"],"contract_sha256":protocol["contract_sha256"]});print(json.dumps({"checks":checks,"protocol":protocol},indent=2))
if __name__=="__main__":main()
