"""Synthetic qualification, never submitted as real model evidence."""
import copy
from phase2748_rdc_generated_identity_audit import *


class ToyTokenizer:
    def decode(self, ids, skip_special_tokens=True):
        assert skip_special_tokens
        return '["red"]'


def main():
    start = time.monotonic(); checks = []
    row = {'question_id': 'toy:1', 'group_id': 'toy', 'cohort': 'synthetic', 'split': 'unit',
           'answer_annotations': [{'required_spans': ['red']}],
           'tokens': {'native_stop_ids': [9], 'input_ids': [2, 3, 4],
                      'teacher_ids_including_EOS': [1, 9], 'teacher_text': '["red"]'}}
    history = {k: row[k] for k in ['question_id', 'group_id', 'cohort', 'split']}
    history.update(generated_ids=[1, 9], generated_text='["red"]', native_EOS=True,
                   maximum_new_tokens=2, censored=False,
                   score=conservative_complete_answer('["red"]', row['answer_annotations'], True))
    arrays = {'generated_ids': np.array([1, 9], np.int64), 'positions': np.array([2, 3], np.int64),
              'statistics': np.array([[1., -0.5], [0.7, -0.2]], np.float64)}
    assert check_history(row, history, arrays, ToyTokenizer(), 2) == 2
    checks.append('valid_stopped_history')
    capped = copy.deepcopy(history); ca = copy.deepcopy(arrays)
    capped.update(generated_ids=[1, 1], native_EOS=False, censored=True,
                  score=conservative_complete_answer('["red"]', row['answer_annotations'], False))
    ca['generated_ids'] = np.array([1, 1], np.int64)
    assert check_history(row, capped, ca, ToyTokenizer(), 2) == 2
    checks.append('valid_cap_separate_from_exact_text')

    def reject_history(label, change):
        h, a = copy.deepcopy(history), copy.deepcopy(arrays); change(h, a)
        try: check_history(row, h, a, ToyTokenizer(), 2)
        except AssertionError: checks.append(label)
        else: raise AssertionError('Failed to reject '+label)

    reject_history('reject_changed_text', lambda h, a: h.update(generated_text='blue'))
    reject_history('reject_changed_score', lambda h, a: h['score'].update(whole_response_exact_and_stopped=False))
    reject_history('reject_wrong_position', lambda h, a: a.update(positions=np.array([3, 4], np.int64)))
    reject_history('reject_early_EOS', lambda h, a: h.update(generated_ids=[9, 1]))
    reject_history('reject_incorrect_cap', lambda h, a: h.update(censored=True))
    reject_history('reject_record_array_ID_mismatch', lambda h, a: a.update(generated_ids=np.array([2, 9], np.int64)))

    first = {'postnorm_BF16': np.array([16256, 16384], np.uint16)}
    ta = {'teacher_ids': np.array([1, 9], np.int64), 'argmax': np.array([1, 8], np.int64),
          'NLL': np.array([0.5, 1.], np.float64), 'entropy_FP64': np.array([1., 0.7], np.float64),
          'postnorm_BF16': np.array([[16256, 16384], [16384, 16256]], np.uint16)}
    teacher = {'question_id': 'toy:1', 'teacher_text': '["red"]', 'teacher_ids_including_EOS': [1, 9],
               'tokens': 2, 'mean_token_NLL': 0.75, 'sum_token_NLL': 1.5,
               'teacher_forced_argmax_token_accuracy': 0.5}
    assert check_teacher(row, teacher, ta, first, arrays) == 2
    checks.append('valid_teacher_separate_from_free_generation')

    def reject_teacher(label, change):
        t, a = copy.deepcopy(teacher), copy.deepcopy(ta); change(t, a)
        try: check_teacher(row, t, a, first, arrays)
        except AssertionError: checks.append(label)
        else: raise AssertionError('Failed to reject '+label)

    reject_teacher('reject_teacher_mean', lambda t, a: t.update(mean_token_NLL=0.5))
    reject_teacher('reject_teacher_first_state', lambda t, a: a.update(postnorm_BF16=np.zeros((2, 2), np.uint16)))
    reject_teacher('reject_teacher_first_choice', lambda t, a: a.update(argmax=np.array([2, 8], np.int64)))
    reject_teacher('reject_teacher_first_entropy', lambda t, a: a.update(entropy_FP64=np.array([2., 0.7])))
    value = {'timestamp': stamp(), 'all_passed': True, 'source': snapshot(__file__),
             'audit_sha256': sha(Path(__file__).with_name('phase2748_rdc_generated_identity_audit.py')),
             'checks': checks, 'seconds': time.monotonic()-start,
             'scope': 'In-memory synthetic identity/scoring fixtures only; no real learned or prospective results are read or generated by this unit.'}
    path = OUT/'unit'/('generated_identity_'+str(time.time_ns())+'.json'); immutable(path, value)
    save(OUT/'unit/generated_identity_current.json', value)
    print('NATURAL_GENERATED_IDENTITY_UNIT_PASS', len(checks), flush=True)


if __name__ == '__main__': main()
