"""Full skeleton addresses and independent checks of unpruned native factors."""
from rdc_construction_common import *
from rdc_construction_parameters import catalog,mlp_factors
from rdc_native_attention_parameters import factors,entries,rotary_matrix,conditioned_score,rotary_module
from rdc_relation_native_parameters import parameter,decode

OUT=BASE/'phase2746/parameter_structure'


def main():
    import torch
    start=time.monotonic();torch.set_num_threads(2)
    source=snapshot(__file__);reader=snapshot(Path(__file__).with_name('rdc_native_attention_parameters.py'))
    immutable(OUT/'protocol.json',{'timestamp':stamp(),'source':source,'reader':reader,
        'checks':'All checkpoint layer matrix shapes and GQA maps. Native MLP first/last units at every block. Attention factors for first/middle/last blocks and first/last query heads, every native input coordinate.',
        'positions':[0,17,113], 'scope':'Architecture/address/algebra qualification, not discovered language structure or a replacement native BF16 forward.',
        'calculus':'QK affine augmented factors include all coordinates and both norm denominators; rotary coefficients are generated by installed original architecture, with BF16 trig values and FP64 contraction.'})
    skeletons=[];mlp_checks=[];attention=[];rng=np.random.default_rng(2746001)
    for key in ['qwen4','qwen14','glm4']:
        meta=catalog(key);c=meta['config'];d=c['hidden_size'];hidden=c['intermediate_size'];heads=c['num_attention_heads'];hd=c['head_dim']
        parameters={r['name']:r for r in meta['parameters']}
        for block in range(c['num_hidden_layers']):
            prefix=f'model.layers.{block}.';p=prefix+'mlp.'
            joined=p+'gate_up_proj.weight' in parameters
            expected={'self_attn.q_proj.weight':[heads*hd,d],
                'self_attn.k_proj.weight':[c['num_key_value_heads']*hd,d],
                'self_attn.v_proj.weight':[c['num_key_value_heads']*hd,d],
                'self_attn.o_proj.weight':[d,heads*hd],'mlp.down_proj.weight':[d,hidden]}
            expected.update({'mlp.gate_up_proj.weight':[2*hidden,d]} if joined else
                {'mlp.gate_proj.weight':[hidden,d],'mlp.up_proj.weight':[hidden,d]})
            for name,shape in expected.items():
                assert parameters[prefix+name]['shape']==shape,(key,block,name)
            for unit in [0,hidden-1]:
                g,u,w=mlp_factors(key,block,unit)
                assert g.shape==u.shape==w.shape==(d,) and all(np.isfinite(x).all() for x in [g,u,w])
                # Independent scalar-offset checks at both residual-axis edges.
                for coord in [0,d-1]:
                    name=p+('gate_up_proj.weight' if joined else 'gate_proj.weight')
                    gt=float(decode(parameter(ROOT,name,MODELS[key])[unit,coord]))
                    name=p+('gate_up_proj.weight' if joined else 'up_proj.weight')
                    ut=float(decode(parameter(ROOT,name,MODELS[key])[(hidden+unit) if joined else unit,coord]))
                    dt=float(decode(parameter(ROOT,p+'down_proj.weight',MODELS[key])[coord,unit]))
                    assert (g[coord],u[coord],w[coord])==(gt,ut,dt)
                mlp_checks.append({'model':key,'block':block,'unit':unit,'fused_gate_up':joined,
                    'all_three_vectors_width':d,'edge_scalar_addresses_equal':True})
            skeletons.append({'model':key,'block':block,'all_shapes_passed':True,
                'all_head_to_KV_head':[h//(heads//c['num_key_value_heads']) for h in range(heads)],
                'gate_parameter':p+('gate_up_proj.weight' if joined else 'gate_proj.weight'),
                'up_parameter':p+('gate_up_proj.weight' if joined else 'up_proj.weight'),
                'up_row_offset':hidden if joined else 0,'MLP_units':hidden,'residual_width':d})
        print('PARAMETER_ALL_LAYERS',key,c['num_hidden_layers'],flush=True)
        for block in [0,c['num_hidden_layers']//2,c['num_hidden_layers']-1]:
            for head in [0,heads-1]:
                f=factors(key,block,head);rq=rotary_matrix(key,113);rk=rotary_matrix(key,17)
                xq=rng.normal(size=d)/np.sqrt(d);xk=rng.normal(size=d)/np.sqrt(d)
                score,sq,sk=conditioned_score(f,xq,xk,rq,rk)
                # Independent torch FP64 augmented-affine contraction uses all
                # native residual coordinates plus an explicit constant bias.
                aq=torch.tensor(np.column_stack([f['Wq'],f['bq']]))
                ak=torch.tensor(np.column_stack([f['Wk'],f['bk']]))
                qq=aq@torch.tensor(np.r_[xq,1.0]);kk=ak@torch.tensor(np.r_[xk,1.0])
                if f['metadata']['has_qk_norm']:
                    qq=qq/torch.sqrt(qq.square().mean()+c['rms_norm_eps'])
                    kk=kk/torch.sqrt(kk.square().mean()+c['rms_norm_eps'])
                qr=torch.tensor(rq)@(torch.tensor(f['gamma_q'])*qq)
                kr=torch.tensor(rk)@(torch.tensor(f['gamma_k'])*kk)
                reference=float((qr*kr).sum()/np.sqrt(hd))
                assert abs(reference-score)<1e-9*max(1,abs(reference))
                # OV includes every source coordinate and the affine V bias.
                output=f['Wo']@(f['Wv']@xk+f['bv'])
                wt=torch.tensor(f['Wo']);vt=torch.tensor(f['Wv'])@torch.tensor(xk)+torch.tensor(f['bv'])
                error=float(np.max(abs(output-(wt@vt).numpy())))
                assert error<1e-10
                packet=entries(key,block,head,d-1,0,d-1,113,17)
                assert len(packet['qk_all_head_component_terms'])==hd
                assert np.isfinite(packet['read_write_factors']).all()
                path=OUT/f'{key}_L{block}_h{head}_scalar_factor_example.npz'
                npz(path,qk_terms=packet['qk_all_head_component_terms'],ov_terms=packet['ov_all_head_component_terms'],
                    all_head_factors=packet['read_write_factors'],query_rotation=rq,key_rotation=rk)
                # Rotary BF16 operation floor: include actual intermediate
                # rounding, instead of pretending R@q in FP64 is bit exact.
                config,rotary,apply=rotary_module(key)
                values=torch.tensor(rng.normal(size=(1,1,1,hd)),dtype=torch.bfloat16)
                cos,sin=rotary(torch.zeros((1,1,hd),dtype=torch.bfloat16),torch.tensor([[113]]))
                native,_=apply(values,values,cos,sin)
                linear=torch.tensor(rq@values[0,0,0].float().numpy(),dtype=torch.bfloat16)
                floor=float((linear.float()-native[0,0,0].float()).abs().max())
                attention.append({'model':key,'block':block,'head':head,'KV_head':f['metadata']['kv_head'],
                    'smooth_QK_score':score,'query_RMS_denominator':sq,'key_RMS_denominator':sk,
                    'independent_augmented_QK_abs_error':abs(reference-score),'all_coordinate_OV_max_error':error,
                    'native_BF16_rotary_intermediate_rounding_max_abs_error':floor,
                    'example_archive':path.relative_to(BASE).as_posix(),'example_sha256':sha(path)})
        print('PARAMETER_ATTENTION_FACTORS',key,'checked',flush=True)
    result={'timestamp':stamp(),'source':source,'reader':reader,'all_passed':True,
        'skeleton_layers':skeletons,'MLP_native_unit_checks':mlp_checks,'attention_checks':attention,
        'seconds':time.monotonic()-start,'new_native_language_samples':0,
        'limits':'Known architecture and FP64 coefficient identities. QK norm denominators, bias, causal mask, softmax, native BF16 rounding and full residual RMSNorm must remain explicit. No semantic edge or fixed all-context effective matrix inferred.'}
    save(OUT/'result.json',result);ledger('phase2746_native_parameter_checks',result['seconds'])
    print('PARAMETER_STRUCTURE_DONE',result['seconds'],flush=True)


if __name__=='__main__':main()
