# -*- coding: utf-8 -*-
"""Phase 2805+2806 artifact hash registry (writes report file; no stdout reliance)."""
import hashlib, os, json, io

BASE = r"D:\AI2050\Ai2050-OpenOne\tests\glm5"
RES = os.path.join(BASE, "result", "rdc_query_construction_20260913")
OUT = os.path.join(BASE, "probe2805_2806_hashes.txt")

TARGETS = [
    (2805, os.path.join(BASE, "phase2805_rdc_entity_law.py")),
    (2805, os.path.join(RES, "phase2805", "qwen4_entity_law", "execution.json")),
    (2805, os.path.join(RES, "phase2805", "qwen4_entity_law", "result.json")),
    (2805, os.path.join(RES, "phase2805", "qwen4_entity_law", "entity.npz")),
    (2806, os.path.join(BASE, "phase2806_rdc_hierarchy.py")),
    (2806, os.path.join(RES, "phase2806", "qwen4_hierarchy", "execution.json")),
    (2806, os.path.join(RES, "phase2806", "qwen4_hierarchy", "result.json")),
    (2806, os.path.join(RES, "phase2806", "qwen4_hierarchy", "hierarchy.npz")),
    (2806, os.path.join(BASE, "run2806.log")),
]

def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()

lines = []
for phase, p in TARGETS:
    if os.path.exists(p):
        sz = os.path.getsize(p)
        lines.append("phase%d | %s | SHA256=%s | %d bytes" % (phase, p, sha256(p), sz))
    else:
        lines.append("phase%d | %s | MISSING" % (phase, p))

with io.open(OUT, "w", encoding="utf-8") as f:
    f.write("=== Phase 2805+2806 hash registry (generated by probe2805_2806_hashes.py) ===\n")
    f.write("\n".join(lines) + "\n")
print("ok")
