export const THEORY_ROUTE_DATA = {
    GPT5: {
        name: 'GPT5 机制闭合路线', phase: 'Phase 344', date: '2026-07-11 00:40', tone: '#38bdf8',
        source: 'research/gpt5/docs/AGI_GPT5_MEMO.md',
        thesis: '语言生成更像上下文条件化的动态运行子图，而不是由固定方向或最大激活神经元独立控制。当前重点是把相关读出压缩为可复制的组件级因果链。',
        verdict: '实验平台与协议门已较成熟；跨模型机制仍未闭合。',
        metrics: [
            ['任务基线', '38 / 48', 'Phase 343 中通过 baseline qualification（基线资格）的模型-任务单元。'],
            ['跨模型复制', '0', 'Phase 344 未发现同时跨三模型复制的粗块因果候选。'],
            ['单神经元闭合', '0 / 72', '候选神经元未达到稳定、必要、充分且低副作用的联合标准。'],
            ['执行稳定路径', '2', 'Phase 342 中仅两条路径在 11 种执行模式下保持稳定。'],
        ],
        stages: [
            { title: '协议资格与可比性', phase: 'Phase 337 / 340 / 343', status: '已建立', detail: '先验证问题是否被模型稳定答对，再允许进入机制测量。显式关系绑定达到 7/9 模型-接口资格；扩展到 16 个任务后，48 个模型-任务单元中 38 个合格。', source: 'Phase 337、340、343' },
            { title: '粗块材料因果筛选', phase: 'Phase 338', status: '局部成立', detail: '对层段与组件进行阻断、替换和恢复，寻找答案 margin 的必要来源。仅 GLM4 出现模型特异的早层 source MLP 候选，三模型共同候选为 0。', source: 'Phase 338' },
            { title: '执行不变性审计', phase: 'Phase 342', status: '边界收紧', detail: '改变 batch、hook、缓存与测量路径，检验候选是否只是实现细节。11 种模式下仅保留两条稳定路径，说明很多早期候选依赖执行条件。', source: 'Phase 342' },
            { title: '一般复制候选关闭', phase: 'Phase 344', status: '否定结果', detail: '13 个任务的单样本粗块审计没有产生跨模型复制候选。当前不能把 GLM4 的短语复制效应上升为通用语言机制。', source: 'Phase 344' },
        ],
        formula: {
            title: '分层因果闭合判据（工作形式）',
            expression: 'C = Q_base · S_exec · N_causal · R_restore · X_replicate',
            explanation: 'Q_base 表示基线答题合格；S_exec 表示执行方式不变；N_causal 表示消融后目标 margin 必然下降；R_restore 表示恢复候选后效应回归；X_replicate 表示跨提示、任务和模型复制。任一门为 0，整体闭合就不能成立。',
            boundary: '这是实验验收逻辑，不是已经发现的语言自然定律；目前 X_replicate 仍为 0。',
        },
        confirmed: ['最高激活值不能替代因果必要性。', '答案对齐接口可显著提高基线资格，但不会自动产生机制闭合。', '上下文、执行接口和任务协议都会改变可见路径。'],
        blockers: ['缺少跨模型、跨任务稳定的最小组件链。', '单神经元证据仍为零，不能把组件效应解释为真实神经元规则。', 'GLM4 的局部效应尚未在 Qwen3 与 DS7B 复制。'],
        next: ['冻结 Phase 342 的稳定执行路径，扩大每任务样本量与随机种子。', '从粗块进入激活加权通道组，并执行消融-恢复-替代三联检验。', '建立负对照族与副作用预算，再尝试跨模型结构对齐。'],
    },
    GLM5: {
        name: 'GLM5 全局结构辨识路线', phase: 'Phase 1236 / C001-WP00', date: '2026-08-11 19:35', tone: '#34d399',
        source: 'research/glm5/docs/AGI_GLM5_MEMO.md',
        thesis: '研究对象已经从固定向量、热点和单层实体升级为类型化功能对象与未来响应：先确认行为构念可识别，再按内容、格式、自然生成和停止缓存分别授权，最后才允许进入干预、救援与跨模型功能同构。',
        verdict: 'C001-WP00 工程闭合；EXP-C001-WP01-001 已预注册但 run_ready=false，当前没有新增内部机制证据。',
        metrics: [
            ['类型化构念', '4', '内容选择、严格格式、自然完整生成、停止与缓存闭合。'],
            ['关键证据记录', '14', 'WP00 已迁移的本地可见关键证据子集，不等于完整 K1–K210 总账。'],
            ['Phase1235 四门', '1·0·1·1', 'candidate、short、sentence、natural；异质总门为 0。'],
            ['WP01 执行资格', 'FALSE', '合同 preregistered，但材料、代码、环境与独立审计器尚未全部冻结。'],
        ],
        stages: [
            { title: '已知真值相机校准', phase: 'Phase 1151–1201', status: '边界建立', detail: '双路径、冗余、协同、响应商、形成事件和联盟救援相机在已知真值网络中校准，并接受自由网络外部效度检验。结果证明相机可工作，但适用域和可识别性必须逐项登记。', source: 'Phase 1151–1201' },
            { title: '类型化功能对象', phase: 'Phase 1202–1228', status: '局部成立', detail: '对象—属性绑定、操作行为和生成时间被拆成独立对象；获得五个行为原子与若干 Qwen3 局部因果拼图，同时排除单点边界和固定数值域承载完整机制的强版本。', source: 'Phase 1202–1228' },
            { title: '七读出正交判决', phase: 'Phase 1229–1235', status: '类型边界', detail: '在全新 96 个 axis-world 上，候选评分、固定句式和自然内容稳定，严格短字符串合同失败。结果支持类型化行为响应，不支持隐藏内容模块。', source: 'K206–K210' },
            { title: 'C001 研究操作系统', phase: 'Phase 1236', status: 'WP00 完成', detail: '关键证据、假说、拼图、对象、构念、合同、权限与不可变清单进入机器可校验系统；WP01 保持 run_ready=false。', source: 'Phase 1236 / D001–D006' },
        ],
        formula: {
            title: '类型化行为与运行授权（实验合同）',
            expression: 'b(x,q)=(B_choice,…,B_natural);  Authorize_run ⇔ ∧ prerequisites = 1',
            explanation: '行为不是一个总准确率，而是候选评分、受限解码、短串、句式和自然生成等读出的联合向量。只有代码、材料、反泄漏负控、环境清单和独立审计全部冻结，WP01 才能从 preregistered 升级为 ready。',
            boundary: '这是证据与权限合同，不是神经网络内部自然定律；当前 Authorize_run=0。',
        },
        confirmed: ['输出实现对读出类型、模板、前缀和全词表竞争条件化。', '候选排序、格式服从、自然内容和停止缓存不能互相替代证据。', '机器可拒绝的冻结合同能够阻止成功子集越权进入 hidden 扫描。'],
        blockers: ['尚无通过跨读出资格门的全新自然功能对象。', '没有在当前对象上采集未来响应、必要性、救援或中介证据。', '没有跨 Qwen3、GLM4、DS7B 的功能同构闭合，也不能外推到人脑。'],
        next: ['完成 WP01 全新材料和多参考功能等价合同的无模型生成。', '冻结反泄漏负控、环境清单、代码哈希与独立审计器，使 run_ready 由机器裁决。', '只有 WP01 行为与构念双门通过后，才设计未来响应张量、错误供体、必要性和救援实验。'],
    },
    Gemini: {
        name: 'Gemini 几何与可控性路线', phase: 'Phase XV–XVIII / Stage 83–85', date: '2026-04-08', tone: '#f472b6',
        source: 'research/gemini/docs/AGI_GEMINI_MEMO.md',
        thesis: '把残差流视为受局部曲率、范数增长和上下文稳定性约束的动力系统，研究为什么隐空间操控容易失真，以及局部几何能否成为机制坐标。',
        verdict: '提出了有价值的物理约束与反例；部分宏观理论仍超出真实模型证据。',
        metrics: [
            ['操控实验', '28', 'Phase XV–XVIII 汇总的三模型操控实验数量。'],
            ['模型范围', '3', 'GLM4、Qwen3、DeepSeek 7B。'],
            ['范数稀释', '699×–3234×', '记录中报告的深层残差范数稀释范围。'],
            ['logit 效率', '11.5×', '记录中报告的 logit 空间相对隐空间操控效率。'],
        ],
        stages: [
            { title: '理论真实性审计', phase: '2026-03-22', status: '严格降级', detail: '审计指出全局数学叙事、类脑类比与局部模型证据之间存在跨度，要求把假说、toy 结果和真实模型干预分层。', source: '理论体系深度审计' },
            { title: '操控不可能三角', phase: 'Phase XV–XVIII', status: '工作假说', detail: '控制强度、语义保真与上下文稳定很难同时最大化。强干预可能提高目标 rank，却破坏困惑度和自然生成轨迹。', source: '2026-04-08 操控物理极限分析' },
            { title: '曲率与架构差异', phase: 'Phase XV–XVIII', status: '模型特异', detail: '记录将 GLM4 描述为对扰动敏感、Qwen3 描述为具有较强回拉。该现象提示步长与干预策略不能直接跨模型复用。', source: 'Hessian 符号反转小节' },
            { title: '下一代路线', phase: 'Stage 83–85', status: '待验证', detail: '局域化重整化、分段流形切换与主动因果环是研究提案，目前不能作为已证实语言原理。', source: '2026-03-22 路线图' },
        ],
        formula: {
            title: '操控三目标约束（概念形式）',
            expression: 'maximize (Strength, Fidelity, Stability)  subject to  ΔE(x) ≤ C_local',
            explanation: 'Strength 是目标行为改变幅度；Fidelity 是非目标语义与语言质量保持程度；Stability 是跨上下文和后续 token 的持续性；C_local 表示局部状态可承受的扰动预算。',
            boundary: '这是对实验现象的约束表达，不是已经证明的守恒定律；C_local 目前没有统一可测定义。',
        },
        confirmed: ['隐空间强干预可能被后续层稀释或回拉。', 'logit 操控高效但绕过内部机制，不能当作机制解释。', '不同模型对同一干预的响应存在显著架构差异。'],
        blockers: ['曲率符号与“物理地形”的解释仍需更严格数值复核。', '范数增长不能单独推出信息被稀释。', 'Stage 83–85 尚是理论任务，不是实验闭合成果。'],
        next: ['复跑 28 项实验并统一保存逐样本、随机种子和对照结果。', '把曲率、范数和行为 margin 放进同一因果实验，不再仅凭几何量推断机制。', '选取与 GPT5/GLM5 相同任务，验证局部曲率是否能预测通道因果效应。'],
    },
};
