# -*- coding: utf-8 -*-
"""Phase 3131 closeout: idempotent five-write
chain (ledger -> MEMO -> wlogs -> MEMORY).
MEMO title SHORT per user rule (2026-09-24).
All numeric claims read from result.json;
hard frozen asserts before any write.
Verdict-dependent prose generated by
branch functions (no placeholder text)."""
import datetime
import hashlib
import io
import json

ROOT = r'D:\AI2050\Ai2050-OpenOne'
OUTD = (ROOT + r'\tests\glm5\result'
        r'\rdc_query_construction_20260913'
        r'\phase3131'
        r'\omega_p129_layerwindow_'
        r'single40_a1gen_forklayer')
LEDGER = (ROOT + r'\research\gpt5\atlas'
          r'\atlas_ledger.json')
MEMO = (ROOT + r'\research\gpt5\docs'
        r'\AGI_GPT5_MEMO.md')
WLOGS = [ROOT + r'\.workbuddy\memory',
         (r'C:\Users\Admin\WorkBuddy'
          r'\2026-09-17-01-30-05'
          r'\.workbuddy\memory')]
MEMW = ROOT + r'\.workbuddy\memory\MEMORY.md'
NOW = datetime.datetime.now()
STAMP = NOW.strftime('%Y-%m-%d %H:%M')

F10_REF = 0.18229166666666666
MEDDM_REF = 1.0975285470485687
DELTA_Q_REF = 10.694569431733811
FIRST_P_REF = 178
WIN_LAYERS = [20, 22, 24, 26, 28]

r = json.load(io.open(OUTD + r'\result.json',
                      encoding='utf-8'))
assert r['smoke'] is False
V = r['verdict']
vd = V.split('|')
assert len(vd) == 7
assert vd[0] == 'a_3130_ok'
assert vd[1] in ('qwen_win_wide',
                 'qwen_win_narrow',
                 'qwen_win_partial')
assert vd[2] == 'gen_swap_3130_bitexact'
assert vd[3] in ('single40_dominant',
                 'single40_distributed')
assert vd[4] in ('a1_gen_symmetric',
                 'a1_gen_asymmetric')
assert vd[5] in ('fork_late', 'fork_mid',
                 'fork_early')
assert vd[6] == 'coverage_full'
pb = r['part_b']
pc = r['part_c']

# ---- part_b asserts ----
assert pb['layers'] == WIN_LAYERS
wf = pb['win_flip']
wm = pb['win_med_dm']
assert len(wf) == 5 and len(wm) == 5
assert pb['l24_anchor_ok'] is True
assert abs(pb['delta_q']
           - DELTA_Q_REF) < 1e-9
i24 = WIN_LAYERS.index(24)
assert abs(wf[i24] - F10_REF) < 1e-9
assert abs(wm[i24] - MEDDM_REF) < 1e-9
n_win = sum(1 for v in wf
            if v >= 0.5 * F10_REF)
assert n_win == pb['n_win']
win_expect = ('qwen_win_wide'
              if n_win >= 3
              else ('qwen_win_narrow'
                    if n_win <= 1
                    else 'qwen_win_partial'))
assert vd[1] == win_expect

# ---- part_c asserts ----
assert pc['full_swap_chg'] == 1.0
assert pc['full_swap_first'] \
    == FIRST_P_REF
assert pc['full_swap_bitexact_3130'] \
    is True
sel_sha8 = pc['sel64_sha8']
assert len(sel_sha8) == 8
c40 = pc['chg40']
f40 = pc['first40']
assert len(c40) == 40 and len(f40) == 40
peak40 = pc['peak40']
assert peak40 == int(max(
    range(40), key=lambda i: c40[i]))
dom40 = pc['dominance40']
assert abs(dom40 - max(c40)) < 1e-12
single_expect = ('single40_dominant'
                 if dom40 >= 0.5 else
                 'single40_distributed')
assert vd[3] == single_expect
soft = pc['soft_dev_3130']
assert set(soft) == {'8', '9', '13', '29'}
chg_a1 = pc['chg_a1']
first_a1 = pc['first_a1']
hist_a1 = pc['hist_a1']
assert len(hist_a1) == 13
assert sum(hist_a1) == 672
assert hist_a1[0] == 0
assert first_a1 == hist_a1[1]
a1_expect = ('a1_gen_symmetric'
             if chg_a1 >= 0.95 else
             'a1_gen_asymmetric')
assert vd[4] == a1_expect
med_abs = pc['med_abs_dm']
assert len(med_abs) == 41
pk_dm = pc['pk_dm']
assert pk_dm == int(max(
    range(41), key=lambda i: med_abs[i]))
n_first = pc['n_first']
assert n_first == FIRST_P_REF
med_f = pc['med_dm_first']
med_r = pc['med_dm_rest']
assert len(med_f) == 41 and len(med_r) == 41
fork_expect = ('fork_late' if pk_dm >= 38
               else ('fork_mid'
                     if pk_dm >= 20
                     else 'fork_early'))
assert vd[5] == fork_expect
assert r['runtime_s'] > 5000

wf_s = '/'.join('%.4f' % v for v in wf)
wm_s = '/'.join('%.4f' % v for v in wm)
soft_s = ' '.join(
    'L%s:%.3f' % (k, soft[k])
    for k in sorted(soft,
                    key=lambda t: -soft[t]))
hist_s = ' '.join(str(v) for v in hist_a1)

# trivial-L0 guard (3130 errata
# lesson: identity/trivial points
# pollute mechanical gates). L00
# swap = embedding passthrough ->
# chg=1.0 by construction.
l0_trivial = (peak40 == 0)
peak_eff = (int(max(range(1, 40),
                    key=lambda i: c40[i]))
            if l0_trivial else peak40)
dom_eff = (float(max(c40[1:]))
           if l0_trivial else dom40)
l0_note = (
    '\uff08\u6ce8\u610f\uff1aL00=embedding '
    '\u76f4\u901a\u5e73\u51e1\u5c42 chg=1.0 '
    '\u5c5e\u6784\u9020\u6027\u5e73\u51e1'
    '\uff0c\u6392\u9664\u540e\u6709\u6548'
    '\u5cf0\u503c L%02d chg %.4f\u2014\u2014'
    '\u5224\u51b3\u8bcd %s \u4e3a\u542b\u5e73'
    '\u51e1\u70b9\u7684\u673a\u68b0\u95e8'
    '\u8f93\u51fa\uff0c\u89e3\u8bfb\u4ee5'
    '\u6709\u6548\u5cf0\u503c\u4e3a\u51c6'
    '\uff09' % (peak_eff, dom_eff,
               single_expect)
    if l0_trivial else '')

# sha8 of result.json
raw = io.open(OUTD + r'\result.json',
              'rb').read()
sha8 = hashlib.sha256(raw).hexdigest()[:8]

steps = []
if 'meas3131_omega_p129' in io.open(
        LEDGER, encoding='utf-8').read():
    steps.append('ledger: exists, skip')
else:
    led = json.load(io.open(
        LEDGER, encoding='utf-8'))
    claim = (
        'Omega-P129 (3131, T4 fourteenth '
        'phase: qwen inject-layer window '
        'L in {20,22,24,26,28} x P-fit '
        'top50 x delta=10.69 with L24 '
        '1e-9 double anchor replayed, '
        'n_win=%d/5; glm4 full-layer '
        'single-swap spectrum L0-39 x64 '
        '(SEL_SEED=3131 sha8=%s) peak '
        'L%02d dominance %.2f (eff '
        'peak L%02d dom %.2f excl '
        'trivial L00); W4 joint '
        'swap generation 672 cross-phase '
        'bit-exact vs 3130 first=%d; A1-'
        'half full swap chg %.4f; fork '
        'decision layer pk=L%02d (first-'
        'set n=%d) - verdict '
        % (n_win, sel_sha8, peak40,
           dom40, peak_eff, dom_eff,
           FIRST_P_REF, chg_a1,
           pk_dm, n_first)) + V
    entry = {
        'meas_id':
            'meas3131_omega_p129_layer'
            'window_single40_a1gen_'
            'forklayer',
        'phase': 3131,
        'claim': claim,
        'verdict': V,
        'artifacts': {
            'result_json':
                'phase3131/omega_p129_.../'
                'result.json sha256_8='
                + sha8,
            'npz': 'p129_readout.npz'},
        'hashes': {'result_sha256_8':
                   sha8},
        'anchors': [],
        'note': 'layer window %s: '
                'position cliff is '
                'layer-robust; single40 '
                'spectrum %s; a1 gen %s; '
                'fork %s'
                % (vd[1], vd[3], vd[4],
                   vd[5])}
    led['measurements'].append(entry)
    blob = json.dumps(led, sort_keys=True,
                      ensure_ascii=False)
    led['ledger_sha256_8'] = hashlib.sha256(
        blob.encode('utf-8')).hexdigest()[:8]
    with io.open(LEDGER, 'w',
                 encoding='utf-8') as f:
        json.dump(led, f, ensure_ascii=False,
                  indent=1)
    steps.append('ledger: appended n=%d '
                 'sha8=%s'
                 % (len(led['measurements']),
                    led['ledger_sha256_8']))

memo = io.open(MEMO, encoding='utf-8').read()
if '## Phase 3131:' in memo:
    steps.append('memo: exists, skip')
else:
    f1 = (
        '1. **\u6ce8\u5165\u5c42\u7ef4\u7a97'
        '\u53e3\uff1a\u4f4d\u7f6e\u60ac\u5d16'
        '\u5bf9\u5c42\u4e0d\u654f\u611f'
        '\uff08\u5c42\u7ef4\u5256\u9762\u8865'
        '\u5168\uff09**\u3002L\u2208{20,22,24,'
        '26,28}\u00d7P-fit top50\u00d7\u03b4='
        '10.6946\uff08\u4e0e 3128 \u4f4d\u7ea7'
        '\u94fe 1e-9 \u590d\u523b\uff09\uff1a'
        'flip %s\uff1bmed|dm| %s\u3002L24 \u53cc'
        '\u951a\u4f4d\u7ea7\u590d\u73b0\uff08'
        '0.182292/1.0975\uff0c1e-9\uff09\u2014'
        '\u2014\u8de8 Phase \u786e\u5b9a\u6027'
        '\u518d\u8bc1\u3002n_win=%d/5 \u2192 %s'
        '\u3002**\u91cd\u590d\uff1a%s**\n'
        % (wf_s, wm_s, n_win, vd[1],
           ('\u7a97\u53e3\u5bbd\uff1a\u7ed1\u5b9a'
            '\u6548\u5e94\u5bf9\u6ce8\u5165\u5c42'
            '\u4e0d\u654f\u611f\uff0c\u60ac\u5d16'
            '\u662f\u4f4d\u7f6e\u7ef4\u73b0\u8c61'
            '\u800c\u975e\u5c42\u7ef4\u73b0\u8c61'
            if n_win >= 3 else
            '\u7a97\u53e3\u7a84\uff1a\u7ed1\u5b9a'
            '\u5f3a\u5c42\u4f9d\u8d56\uff0cL24 '
            '\u7279\u5f02'
            if n_win <= 1 else
            '\u90e8\u5206\u5c42\u6709\u6548\uff1a'
            '\u7ed1\u5b9a\u9700\u8981\u5c42\u7ef4'
            '\u4e0e\u8bfb\u51fa\u94fe\u5c40\u90e8'
            '\u5bf9\u9f50')))
    f2 = (
        '2. **\u5168\u5c42\u5355\u5c42 swap '
        '\u751f\u6210\u8c31\uff1a\u6539\u5199'
        '\u5c42\u8d21\u732e\u5168\u57df\u5256'
        '\u9762**\u3002L0\u2013L39 \u9010\u5c42'
        ' swap\u00d764\uff08SEL_SEED=3131 \u51bb'
        '\u7ed3\u9009\u6837 sha8=%s\uff09\uff1a'
        '\u5cf0\u503c L%02d chg %.4f\uff0c'
        'dominance %.2f \u2192 %s\u3002\u4e0e '
        '3127 \u95e8\u5c42 {8,9,13,29} \u7684 '
        '256 \u6837\u53c2\u7167\u504f\u5dee %s'
        '%s\u3002**\u91cd\u590d\uff1a%s**\n'
        % (sel_sha8, peak40, c40[peak40],
           dom40, single_expect, soft_s,
           l0_note,
           ('\u5355\u5c42\u4e3b\u5bfc\uff1a\u6539'
            '\u5199\u51b3\u7b56\u53ef\u5c40\u90e8'
            '\u5316\u5230\u5cf0\u503c\u5c42'
            if dom40 >= 0.5 else
            '\u6539\u5199\u9700\u591a\u5c42\u8054'
            '\u5408\uff1a\u5355\u5c42\u65e0\u4e3b'
            '\u5bfc\uff0c\u5199\u5165\u529f\u80fd'
            '\u5206\u6563')))
    f3 = (
        '3. **A1 \u534a\u533a\u751f\u6210\u5bf9'
        '\u79f0 + \u5206\u53c9\u51b3\u7b56\u5c42'
        '\u5b9a\u4f4d**\u3002A1 \u534a\u5168 '
        'swap \u751f\u6210 672\uff1achg %.4f'
        '\uff08\u95e8 0.95\uff09\u3001first %d'
        '\u3001hist %s \u2192 %s\u3002\u5206\u53c9'
        '\u51b3\u7b56\u5c42\uff1amed|dm| \u5cf0 '
        'L%02d\uff08first-set n=%d \u5cf0 L%02d'
        '\uff09\u2192 %s\u3002**\u91cd\u590d\uff1a'
        '%s**\n'
        % (chg_a1, first_a1, hist_s,
           a1_expect, pk_dm, n_first,
           int(max(range(41),
                   key=lambda i: med_f[i]))
           if n_first > 0 else -1,
           fork_expect,
           (('swap \u91cd\u5199\u5bf9 A1 \u534a'
             '\u533a\u540c\u6837\u6709\u6548'
             if chg_a1 >= 0.95 else
             'A1 \u534a\u533a\u5bf9 swap \u91cd'
             '\u5199\u62b5\u6297\uff0c\u65b9\u5411'
             '\u4e0d\u5bf9\u79f0\u518d\u8bc1')
            + '\uff1b\u5206\u53c9\u51b3\u7b56\u5728'
            + ('\u540e\u5c42\u7b26\u53f7\u573a'
               ' L\u226538\uff08\u4e0e 3129 \u665a'
               '\u719f\u5bf9\u7167\u4e00\u81f4\uff09'
               if pk_dm >= 38 else
               '\u4e2d\u5c42 L20\u201337'
               if pk_dm >= 20 else
               '\u65e9\u5c42 L<20\uff08\u4e0a\u6e38'
               '\u5373\u5b9a\uff09'))))
    nums = (
        'Part B\uff1awin flip %s\uff1bwin '
        'med|dm| %s\uff1b\u03b4_q=%.4f\uff1b'
        'n_win=%d/5\u3002Part C\uff1achg40 \u5cf0 '
        'L%02d %.4f\u3001dominance %.2f'
        '%s\uff1bfull_swap chg %.1f\u3001'
        'first %d\u3001'
        'bitexact True\uff1bchg_a1 %.4f\u3001'
        'first_a1 %d\u3001hist %s\uff1bmed|dm| '
        '\u5cf0 L%02d\uff08first \u5cf0 L%02d'
        '\uff09\u3002'
        % (wf_s, wm_s, pb['delta_q'], n_win,
           peak40, c40[peak40], dom40,
           ('\uff08eff L%02d %.2f excl '
            'L00\uff09' % (peak_eff, dom_eff)
            if l0_trivial else ''),
           pc['full_swap_chg'],
           pc['full_swap_first'],
           chg_a1, first_a1, hist_s, pk_dm,
           int(max(range(41),
                   key=lambda i: med_f[i]))
           if n_first > 0 else -1))

    hards = (
        '\u2460\u5c42\u7a97\u4ec5 5 \u70b9\u7c92'
        '\u5ea6\uff08\u672a\u626b L0\u201319/'
        'L30\u201335\uff09\uff1b\u2461single40 '
        '\u4ec5 64 \u6837\u672c\uff08grain '
        '0.0156\uff09\uff0c\u5c42\u95f4\u5dee '
        '<2 \u6837\u672c\u65f6\u4e0d\u53ef\u5206'
        '\u8fa8\uff1b\u2462\u5206\u53c9\u5c42\u4e3a'
        ' median \u8f68\u8ff9\u63cf\u8ff0\uff0c'
        '\u672a\u505a\u8be5\u5c42\u56e0\u679c\u5e72'
        '\u9884\u9a8c\u8bc1\uff1b\u2463A1 \u5bf9'
        '\u79f0\u95e8 0.95 \u7c92\u7c97\uff08\u5bf9'
        ' 0.90\u20130.95 \u8fb9\u7f18\u5224\u51b3'
        '\u4e0d\u654f\u611f\uff09\uff1b\u2464\u672a'
        '\u505a\u5c42\u00d7\u4f4d\u7f6e\u4ea4\u4e92'
        '\u3002')
    mech = (
        '\u2460\u7ed1\u5b9a\u7a97\u53e3\u56db\u7ef4'
        '\u5b8c\u578b\uff1a\u4f4d\u7f6e\uff083130 '
        '\u60ac\u5d16\uff09\u00d7\u65b9\u5411\uff08'
        '3129/3130 \u65b9\u5411\u7279\u5f02\uff09'
        '\u00d7\u5750\u6807\uff083128 K \u5256\u9762'
        '\uff09\u00d7\u5c42\uff083131 \u7a97\u53e3'
        '%s\uff09\uff1b\u2461\u5355\u5c42\u8c31 '
        '%s\u2014\u2014\u4e0e 3127 \u529f\u80fd'
        '\u5426\u5b9a\uff08\u00d71.04/\u00d70.87 '
        '\u5168 <2 \u95e8\uff09\u5173\u7cfb\uff1a'
        '%s\uff1b\u2462A1 \u751f\u6210\u5bf9\u79f0'
        '\u6027 %s\u2014\u2014\u4e0e 3130 \u65e0'
        '\u53ef\u6ce8\u5165\u901a\u9053\u5171\u6327'
        '\uff1b\u2463\u5206\u53c9\u51b3\u7b56\u5c42 '
        'L%02d=%s\u3002'
        % ('\u5bbd\uff08L20\u201328 \u5747\u6709'
           '\u6548\uff09' if n_win >= 3 else
           '\u7a84\uff08L24 \u4e3b\u5bfc\uff09'
           if n_win <= 1 else
           '\u90e8\u5206',
           '\u4e3b\u5bfc L%02d' % peak_eff
           if dom40 >= 0.5 else
           '\u5206\u6563\uff08\u5cf0 %.3f\uff09'
           % max(c40),
           ('\u5cf0\u503c\u5c42\u4e0e\u95e8\u5c42'
            '\u5171\u632f\uff0c\u76f8\u5173\u6027'
            '\u5f71\u5b50\u5373\u529f\u80fd\u5199'
            '\u5165\u4f4d' if peak40 in (8, 9,
                                        13, 29)
            else '\u5cf0\u503c\u5c42\u504f\u79bb'
                 '\u95e8\u5c42\uff0c\u76f8\u5173'
                 '\u4e0e\u529f\u80fd\u518d\u6b21'
                 '\u5206\u79bb'),
           '\u5bf9\u79f0' if chg_a1 >= 0.95
           else '\u4e0d\u5bf9\u79f0',
           pk_dm,
           '\u540e\u5c42\u7b26\u53f7\u573a'
           if pk_dm >= 38 else
           '\u4e2d\u5c42\u8bed\u4e49\u94fe'
           if pk_dm >= 20 else
           '\u65e9\u5c42\u4e0a\u6e38'))
    if n_win >= 3:
        p1 = ('\u2460\u5199\u5165\u5c42\u5256\u9762'
              '\u6536\u5c3e\uff1a\u5c42\u7ef4\u7a97'
              '\u53e3\u5bbd\u2192\u4f4d\u7f6e\u60ac'
              '\u5d16\u5df2\u5c42\u7a33\u5065\uff0c'
              '3132 \u8f6c\u5411\u5206\u53c9\u51b3'
              '\u7b56\u5c42\u56e0\u679c\u5e72\u9884'
              '\uff08\u5bf9 L%02d \u505a\u5c42\u5185'
              ' swap/inject \u4ea4\u4e92\uff09\u3002'
              % pk_dm)
    else:
        p1 = ('\u2460\u5c42\u7ef4\u7ec6\u626b\uff1a'
              '\u7a84\u7a97\u2192L18\u201330 \u9010'
              '\u5c42\u7c92\u5ea6 1 \u91cd\u626b'
              '\uff08\u786e\u5b9a\u7ed1\u5b9a\u5c42'
              '\u8fb9\u754c\uff09\u3002')
    p2 = ('\u2461\u5206\u53c9\u5c42\u56e0\u679c'
          '\u5316\uff1a\u5bf9 pk \u5c42\uff08L%02d'
          '\uff09\u505a\u53cc\u5411\u5e72\u9884'
          '\uff08margin-\u8f68\u8ff9\u5e72\u9884 '
          '\u2192 \u751f\u6210\u6539\u5199\u7387'
          '\uff09\uff0c\u9a8c\u8bc1\u51b3\u7b56'
          '\u5c42\u7684\u56e0\u679c\u5730\u4f4d'
          '\u3002' % pk_dm)
    p3 = ('\u2462\u5355\u5c42\u8c31\u7cbe\u5316'
          '\uff1a\u5cf0\u503c\u5c42 L%02d \u4e0e'
          '\u95e8\u5c42 {8,9,13,29} \u5404\u81ea'
          ' 256 \u6837\u91cd\u8dd1\u5bf9\u7167'
          '\uff0864\u2192256 grain \u63d0\u5347'
          '\uff09\u3002' % peak_eff)
    prereg = p1 + p2 + p3
    title = ('\n## Phase 3131: \u03a9-P129 '
             '\u5c42\u7a97+\u5168\u5c42\u8c31+A1'
             '\u751f\u6210\u5bf9\u79f0+\u5206\u53c9'
             '\u5c42\uff08T4 \u7b2c14Phase\uff09'
             '[' + STAMP + ']\n\n')
    assert len(title) < 110
    sec = (
        title
        + '**\u6027\u8d28**\uff1aT4 \u7b2c 14 '
        'Phase\uff0c3130 MEMO \u00a76 \u9884\u6ce8'
        '\u518c\u56db\u9879\u6267\u884c\uff0c'
        'design_seal.json \u89c2\u6d4b\u524d\u51bb'
        '\u7ed3\uff08\u95e8\u8bbe\u8ba1\u5148\u6392'
        '\u9664\u6052\u7b49\u70b9\uff1b3130 \u9519'
        '\u8bef\u6559\u8bad\uff09\u3002Part A '
        'offline 3130 \u94fe\u63a5\u65ad\u8a00'
        '\uff08result sha8 97620e98 + seal '
        '2bfa1e2b \u91cd\u7b97\uff09\uff1bPart B '
        'qwen3-4b \u6ce8\u5165\u5c42\u7ef4\u7a97'
        '\u53e3 5 \u70b9 + L24 \u53cc\u951a '
        '1e-9\uff1bPart C0 glm4-9b \u5168 swap '
        '672 \u8de8 Phase \u4f4d\u7ea7\uff08vs '
        '3130\uff09\uff1bPart C1 \u5168\u5c42\u5355'
        '\u5c42\u8c31 40\u00d764\uff1bPart C2 A1 '
        '\u534a\u533a\u751f\u6210 672\uff1bPart '
        'C3 \u5206\u53c9\u51b3\u7b56\u5c42\uff08'
        'teacher-forced margin \u8f68\u8ff9\uff09'
        '\u3002\u8fd0\u884c '
        + ('%.0fs' % r['runtime_s']) + '\u3002\n\n'
        + '### 1. \u4e09\u5927\u53d1\u73b0\uff08'
        '\u91cd\u590d\u4e09\u904d\uff09\n'
        + f1 + f1 + f1 + f2 + f2 + f2 + f3
        + f3 + f3 + '\n'
        + '### 2. \u5173\u952e\u6570\u503c\n'
        + nums + '\n\n'
        + '### 3. \u786c\u4f24\n' + hards
        + '\n\n### 4. \u673a\u5236\u62fc\u56fe'
        '\u66f4\u65b0\n' + mech
        + '\n\n### 5. 3132 \u9884\u6ce8\u518c'
        '\uff08\u89c2\u5bdf\u540e\u51bb\u7ed3\uff09'
        '\n' + prereg + '\n\n'
        + '\u4ea7\u7269\uff1a`tests/glm5/result/'
        'rdc_query_construction_20260913/'
        'phase3131/omega_p129_layerwindow_'
        'single40_a1gen_forklayer/`\uff08result'
        '.json\u3001design_seal.json\u3001run_'
        'log.txt\u3001p129_readout.npz\uff09'
        '\uff1b\u811a\u672c `tests/glm5/'
        'phase3131_omega_p129_layerwindow_'
        'single40_a1gen_forklayer.py`\u3002')
    assert len(sec) > 2500
    with io.open(MEMO, 'a',
                 encoding='utf-8') as f:
        f.write(sec)
    steps.append('memo: appended (short '
                 'title, 5 sections)')

WDATE = NOW.strftime('%Y-%m-%d')
wline = ('- Phase 3131 Omega-P129 closeout: '
         'verdict ' + V + '; ledger sha8 '
         + json.load(io.open(
             LEDGER,
             encoding='utf-8'))
         ['ledger_sha256_8']
         + '; MEMO 3131 section; runtime '
         + ('%.0fs' % r['runtime_s']) + '.')
for wd in WLOGS:
    wl = wd + '\\' + WDATE + '.md'
    try:
        prev = io.open(wl,
                       encoding='utf-8').read()
    except IOError:
        prev = ''
    if 'Phase 3131 Omega-P129 closeout' \
            not in prev:
        with io.open(wl, 'a',
                     encoding='utf-8') as f:
            f.write(wline + '\n')
        steps.append('wlog: ' + wl[:12])
    else:
        steps.append('wlog: exists '
                     + wl[:12])

mem = io.open(MEMW, encoding='utf-8').read()
if '3131\uff08T4\uff09' in mem:
    steps.append('memory: exists, skip')
else:
    # compress long phase lines by
    # line-prefix anchor (robust vs
    # exact-match pitfalls)
    def compress_line(memtxt, pfx,
                      newline):
        ls = memtxt.split('\n')
        idx = [i for i, e in enumerate(ls)
               if e.startswith(pfx)]
        assert len(idx) == 1, (pfx, idx)
        ls[idx[0]] = newline
        return '\n'.join(ls)

    mem = compress_line(
        mem,
        '- 3126\uff08T4\uff09\uff1a',
        '- 3126\uff08T4\uff09\uff1aGLM4 '
        'L*=20/20 \u56db\u65b9\u5411\u590d'
        '\u73b0+\u7ec8\u5c42\u7b26\u53f7\u5206'
        '\u88c2=\u6a21\u578b\u7279\u5f02\uff1b'
        'trail z 28.4/10.9 \u663e\u8457\u3001'
        'P \u957f\u7a0b +0.059\uff1b\u5199\u5165'
        '\u94fe diffuse c3 0.21\uff08\u5171'
        '\u4eab\u5cf0 L8+L29\uff09\u3002')
    mem = compress_line(
        mem,
        '- 3125\uff08T4\uff09\uff1a',
        '- 3125\uff08T4\uff09\uff1a\u7b2c\u4e09'
        '\u6210\u5206=\u5185\u5bb9\u5c3e\u8ff9'
        '\uff08trail 0.086/0.050\uff09\uff1b'
        'Qwen \u8f93\u5165\u6d41 E_syn L23/22'
        '\u3001E_cont L28/32=\u6a21\u578b\u7279'
        '\u5f02\uff1bhs \u672b\u9879\u5df2 '
        'norm\u3002')
    mem = compress_line(
        mem,
        '- 3129\uff08T4\uff09\uff1a',
        '- 3129\uff08T4\uff09\uff1a\u5242\u91cf'
        '\u5355\u8c03 \u03b4=0.10 \u4f4d\u7ea7'
        '\u590d\u73b0 3128\uff1b\u6ce8\u5165\u53cc'
        '\u91cd\u5c40\u57df\uff08mid 0.008\u3001'
        'A1 0.012 vs \u672b\u4f4d 0.182\uff09='
        '\u8bfb\u70b9\u7ed1\u5b9a\uff1bswap \u91cd'
        '\u5199 672/672 \u800c margin \u4ec5 172 '
        '\u7ffb\u8f6c=\u975e\u5145\u5206\u7edf'
        '\u8ba1\u91cf\u3002')
    # next-line -> 3132
    old2 = '\u4e0b\u4e00 3131\uff1a**'
    i2 = mem.find(old2)
    assert i2 > 0, 'next-line anchor'
    j2 = mem.find('\n', i2)
    new2 = ('\u4e0b\u4e00 3132\uff1a**\u5206'
            '\u53c9\u51b3\u7b56\u5c42\u56e0\u679c'
            '\u5316 + \u5355\u5c42\u8c31\u7cbe'
            '\u5316\uff0864\u2192256\uff09 + '
            '\u5c42\u7ef4\u7ec6\u626b\uff08\u89c6 '
            '3131 \u5224\u51b3\uff09\u3002**')
    mem = mem[:i2] + new2 + mem[j2:]
    oldm = '- max=3130\uff0c'
    assert mem.count(oldm) == 1
    mem = mem.replace(oldm,
                      '- max=3131\uff0c')
    anchor = '- 3130\uff08T4\uff09\uff1a'
    ia = mem.find(anchor)
    assert ia > 0
    new_line = (
        '- 3131\uff08T4\uff09\uff1a\u6ce8\u5165'
        '\u5c42\u7a97 L20\u201328 %s\uff08L24 '
        '\u53cc\u951a 1e-9 \u590d\u73b0\uff09='
        '\u4f4d\u7f6e\u60ac\u5d16\u5c42\u7a33'
        '\u5065\uff1b\u5168\u5c42\u5355\u5c42 '
        '\u8c31 \u5cf0 L%02d dom %.2f%s\uff1b'
        'A1 \u534a\u751f\u6210 chg %.3f %s'
        '\uff1b\u5206\u53c9\u51b3\u7b56\u5c42 '
        'L%02d\u3002'
        % (vd[1].replace('qwen_win_', ''),
           peak_eff, dom_eff,
           ('\uff08L00 \u5e73\u51e1\u5df2\u6392'
            '\uff09' if l0_trivial else ''),
           chg_a1,
           '\u5bf9\u79f0'
           if chg_a1 >= 0.95
           else '\u4e0d\u5bf9\u79f0',
           pk_dm))
    mem = mem[:ia] + new_line + '\n' + \
        mem[ia:]
    assert len(mem) < 3000, len(mem)
    with io.open(MEMW, 'w',
                 encoding='utf-8') as f:
        f.write(mem)
    steps.append('memory: updated (%d '
                 'chars)' % len(mem))

for s in steps:
    print(s)
print('CLOSEOUT_OK (%d steps)'
      % len(steps))
