export const CURRENT_RESEARCH_STATE = {
  phase: 1236,
  latestEngineeringPhase: 1241,
  title: 'C001-WP00 不可变证据迁移与冻结合同闭合',
  status: 'blocked',
  statusLabel: 'WP00 已闭合 · WP01 尚不可运行',
  summary: '研究已从连续追加局部 Phase 转入 C001 全局结构辨识战役：关键历史证据已迁移为可追踪对象，内容、格式、自然生成与停止缓存被拆成独立构念；WP01 合同已经预注册，但代码、材料、环境与独立审计器尚未全部冻结，因此 run_ready=false。',
  boundary: '当前最强进展是类型化行为边界、功能对象和证据权限系统，不是语言机制已经破解。Phase1235 只证明同一对象查询在候选评分、短串、固定句式与自然内容读出之间表现不同；没有采集 hidden、attention、head、MLP 或 neuron，也没有建立跨模型因果同构。',
  stopReason: 'Phase1235 的四类资格门为 (candidate, short, sentence, natural)=(1,0,1,1)。短字符串合同失败使异质总门为 0；冻结规则禁止从成功子集追溯授权内部扫描。Phase1236 只完成研究操作系统和冻结合同，不能把工程闭合写成科学正证据。',
  nextTask: '完成 EXP-C001-WP01-001 的无模型材料生成、反泄漏负控、环境清单和独立审计器冻结；只有机器审计把 run_ready 明确升级为 true，才允许按冻结合同运行 Qwen3，且不得自动跨模型或采集内部状态。',
  campaign: {
    id: 'C001',
    workPackage: 'WP01',
    contractId: 'EXP-C001-WP01-001',
    contractStatus: 'preregistered',
    runReady: false,
    modelRuns: 0,
  },
  registry: {
    hypotheses: 9,
    puzzles: 14,
    tests: 13,
    evidence: 14,
    phases: 14,
    decisions: 6,
    objects: 2,
    constructs: 4,
  },
};

export const RESEARCH_EVIDENCE_GATES = [
  {
    id: 'historical-evidence',
    shortLabel: '历史证据',
    label: '关键证据不可变迁移',
    status: 'passed',
    value: '14 条',
    phase: 'Phase 1236 · WP00',
    summary: 'K190–K200、K203、K210 等本地可见关键证据被迁移为带来源、适用域和权限边界的注册记录。',
    detail: '这是关键子集迁移，不是假装 K1–K210 已形成完整总账。缺失条目必须逐条从冻结原文迁移。',
  },
  {
    id: 'typed-constructs',
    shortLabel: '类型化构念',
    label: '内容、格式、生成与停止分账',
    status: 'passed',
    value: '4 类',
    phase: 'Phase 1235-1236',
    summary: '内容选择、严格格式、自然完整生成、停止与缓存闭合被登记为四种不可互相替代的研究构念。',
    detail: '一个构念通过不能自动授权另一个构念，更不能推出四个独立神经模块。',
  },
  {
    id: 'typed-readout',
    shortLabel: '七读出边界',
    label: '类型化行为响应向量',
    status: 'passed',
    value: '1 · 0 · 1 · 1',
    phase: 'Phase 1235 · K210',
    summary: '候选、短串、固定句式、自然内容四类门分别为 1、0、1、1，证明读出合同会改变行为结果。',
    detail: 'K210 是行为与 token-rank 边界，不是 hidden state、生成模块或内部因果机制发现。',
  },
  {
    id: 'behavior-object',
    shortLabel: '行为对象',
    label: '跨读出资格总门',
    status: 'blocked',
    value: '总门 0',
    phase: 'Phase 1232-1235',
    summary: '多个对象绑定材料在局部读出上很强，但没有同时满足预注册的跨接口稳定性与自然生成资格。',
    detail: '不能从候选评分、固定句式或自然内容成功子集出发，绕过短串失败扫描内部状态。',
  },
  {
    id: 'research-os',
    shortLabel: '研究操作系统',
    label: 'C001-WP00 工程闭合',
    status: 'passed',
    value: '校验通过',
    phase: 'Phase 1236 · WP00',
    summary: '注册表、对象、构念、裁决、不可变清单和冻结合同已经形成机器可拒绝的权限链。',
    detail: '工程系统通过只说明实验纪律可执行，不增加任何语言机制证据。',
  },
  {
    id: 'wp01',
    shortLabel: 'WP01 执行资格',
    label: '全新功能等价构念预审计',
    status: 'blocked',
    value: 'run_ready=false',
    phase: 'EXP-C001-WP01-001',
    summary: '合同已预注册，但材料、代码、环境和独立审计器尚未全部冻结，当前只授权无模型预审计。',
    detail: '机器不得运行 Qwen3、自动跨模型或采集 hidden，直到所有先决条件通过并形成新的不可变清单。',
  },
  {
    id: 'mechanism-closure',
    shortLabel: '机制闭合',
    label: '响应、干预、救援与生成闭合',
    status: 'pending',
    value: '0',
    phase: 'C001 后续工作包',
    summary: '尚未在合格自然对象上完成未来响应张量、必要性、充分性、错误供体、救援、中介和完整生成的联合验证。',
    detail: '只有跨材料预测成立并通过干预、救援和负控，才有资格讨论相对脉络结构或跨模型功能同构。',
  },
];

export const RESEARCH_COMPUTATION_CHAIN = [
  { id: 'evidence', label: '不可变证据', gateId: 'historical-evidence', status: 'passed' },
  { id: 'construct', label: '类型化构念', gateId: 'typed-constructs', status: 'passed' },
  { id: 'readout', label: '七读出边界', gateId: 'typed-readout', status: 'passed' },
  { id: 'object', label: '功能行为对象', gateId: 'behavior-object', status: 'blocked' },
  { id: 'contract', label: 'WP01 冻结合同', gateId: 'wp01', status: 'blocked' },
  { id: 'response', label: '未来响应张量', gateId: 'mechanism-closure', status: 'pending' },
  { id: 'closure', label: '干预救援闭合', gateId: 'mechanism-closure', status: 'pending' },
];

export function getResearchEvidenceGate(gateId) {
  return RESEARCH_EVIDENCE_GATES.find((gate) => gate.id === gateId) || null;
}
