export const CURRENT_SNN_RESEARCH = {
  id: 'SpikeICSPB-3D-MR-PhaseA',
  title: '3D SpikeICSPB 多区域 Phase-A',
  evidenceDate: '2026-03-15',
  evidenceLabel: '最新本地 SNN 冻结实证',
  status: '可运行小型原型',
  boundary: '尚未证明强语言能力、长上下文能力、大规模训练稳定性或生物等价性。',
  tags: ['非 Attention 主干', '局部调制更新', '事件驱动候选', '小型合成测试'],
  architecture: [
    {
      id: 'event-patch',
      label: '事件 Patch 选择',
      code: 'EventPatchSelector',
      detail: '用当前事件与前态选择局部 family patch，避免全序列两两注意力。',
    },
    {
      id: 'section-binding',
      label: '脉冲窗截面绑定',
      code: 'BurstSectionBinder',
      detail: '在短时间窗内组合 token、patch 与前态，形成当前局部对象态。',
    },
    {
      id: 'successor',
      label: '相位门控后继运输',
      code: 'PhaseGatedSuccessorCore',
      detail: '按相位和后继门推进状态；当前最主要瓶颈就在这一步。',
    },
    {
      id: 'readout',
      label: '群体读出',
      code: 'PopulationReadout',
      detail: '由群体状态读出下一 token，而不是把单神经元当作固定符号。',
    },
  ],
  regions: [
    { id: 'syntax', label: '语法区', role: '时序与结构约束' },
    { id: 'semantic', label: '语义区', role: '概念与关系状态' },
    { id: 'memory', label: '记忆区', role: '回放与慢支架固化' },
  ],
  systemModules: [
    '自适应局部半径与稀疏桥预算',
    '跨区域 bridge mixing',
    'replay → slow scaffold 固化',
    'learned homeostasis + bounded clamp',
    'protocol router → population readout',
  ],
  learningRule: {
    label: '局部资格迹 + 调制误差 + 回放固化',
    formula: 'Δwᵢⱼ = ηₗₒc mₜ eᵢⱼ + ηᵣₑₚₗₐy Replayᵢⱼ − ηdecay wᵢⱼ',
    boundary: '当前只形成原型级局部更新，不等于已经解决大规模非 BP 信用分配。',
  },
  modelProfile: {
    measuredParameters: '0.647M',
    regions: 3,
    patchSlots: 64,
    regionHiddenDim: 96,
    trainedScale: '小型原型',
  },
  effects: [
    {
      id: 'engine',
      label: '最小闭环',
      value: '通过',
      tone: 'positive',
      detail: '前向、局部更新、回放和群体读出链可运行。',
    },
    {
      id: 'local-update',
      label: '短程局部更新',
      value: '5.6906 → 4.9753',
      tone: 'positive',
      detail: '一次短上下文稳态测试中的 loss；不能外推为语言能力。',
    },
    {
      id: 'homeostasis',
      label: '稳态调节',
      value: '优势 0.2263',
      tone: 'positive',
      detail: '相对弱化稳态控制的短程稳定性优势。',
    },
    {
      id: 'inventory',
      label: '特征库存',
      value: '36 / 分离比 0.9252',
      tone: 'mixed',
      detail: '仅来自小型合成 micro/meso/macro 概念集。',
    },
    {
      id: 'successor',
      label: '后继质量',
      value: '0.1952',
      tone: 'negative',
      detail: 'next-token margin = −0.0032，归一化熵 = 0.9832。',
    },
    {
      id: 'retention',
      label: '保持/即时学习优势',
      value: '+0.0004 / −0.0001',
      tone: 'negative',
      detail: '相对固定控制几乎没有实质收益。',
    },
  ],
  generation: {
    prompt: 'apple is',
    output: 'iiiiiii iiiii …',
    verdict: '失败样例：出现重复塌缩，不能形成可读语言。',
  },
  scalingPlan: [
    { phase: 'A', parameters: '73.2M', status: '仅结构估算' },
    { phase: 'B', parameters: '357.3M', status: '仅结构估算' },
    { phase: 'C', parameters: '1.30B', status: '仅结构估算' },
  ],
  verified: [
    '小型原型可运行并可执行局部更新',
    '局部拓扑质量与稀疏桥质量同时非零',
    '多区域、回放、稳态控制和协议状态已进入代码路径',
  ],
  unverified: [
    '强语言生成与长程推理',
    '大规模真实语料训练与长期保持',
    '相对 Transformer/BP 的能力或能耗优势',
    '与生物脑编码机制的唯一对应关系',
  ],
  sources: [
    'research/gpt5/code/spike_icspb_3d_multiregion_phasea.py',
    'tests/codex_temp/spike_icspb_3d_homeostatic_control_law_block_20260315.json',
    'tests/codex_temp/spike_icspb_3d_feature_inventory_measurement_block_20260315.json',
    'tests/codex_temp/spike_icspb_3d_successor_quality_audit_block_20260315.json',
    'tests/codex_temp/spike_icspb_3d_retention_instant_learning_benchmark_block_20260315.json',
    'tests/codex_temp/spike_icspb_3d_scaling_readiness_block_20260315.json',
  ],
};

