const { chromium }=require('C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');const path=require('path');
const out=path.resolve('tests/glm5/result/rdc_prefix_atlas_20260910/verification');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1480,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const actions=[];const step=async(name,fn)=>{await fn();actions.push(name);console.log('PREFIX_BROWSER',name);};
 const waitField=()=>page.getByTestId('prefix-field').waitFor({state:'visible',timeout:30000});
 const settle=()=>page.waitForLoadState('networkidle');
 try{
  await page.goto('http://127.0.0.1:5173/rdc-prefix');await waitField();await settle();
  await step('full initial field',async()=>{if(await page.getByTestId('prefix-field').getAttribute('width')!=='2560')throw Error('full width');await page.screenshot({path:path.join(out,'qwen4_initial.png')});});
  await step('raw and zscore',async()=>{await page.getByLabel('前缀归一化',{exact:true}).selectOption('true');await settle();await waitField();await page.getByLabel('前缀颜色映射').selectOption('linear');await page.getByLabel('前缀颜色映射').selectOption('signed-log');});
  await step('last coordinate exact query',async()=>{await page.getByLabel('前缀坐标数',{exact:true}).fill('1');await page.getByLabel('前缀起始坐标',{exact:true}).fill('2559');await settle();await waitField();await page.getByTestId('prefix-field').click({position:{x:20,y:20}});await page.getByTestId('prefix-picked').waitFor();if(!(await page.getByTestId('prefix-picked').innerText()).includes('2559'))throw Error('coordinate');});
  await step('full-token panel',async()=>{await page.getByRole('button',{name:'完整token面板',exact:true}).click();await settle();await waitField();await page.getByLabel('面板层').fill('36');await settle();if(await page.getByTestId('prefix-field').getAttribute('width')!=='2560')throw Error('panel width');});
  await step('all native MLP units',async()=>{await page.getByRole('button',{name:'全部MLP单元',exact:true}).click();await settle();await waitField();if(await page.getByTestId('prefix-field').getAttribute('width')!=='9728')throw Error('MLP width');});
  await step('native parameter last unit',async()=>{await page.getByLabel('前缀原生单元').fill('9727');await page.getByLabel('前缀输入坐标').fill('2559');await page.getByLabel('前缀输出坐标').fill('2559');await page.getByRole('button',{name:'核对真实参数路径'}).click();await page.getByTestId('prefix-native').waitFor();});
  await step('frozen and temporal forecasts',async()=>{await page.getByRole('button',{name:'冻结预测对照'}).click();await settle();await waitField();await page.getByLabel('前缀预测器').selectOption('temporal_full_linear');await settle();await page.getByTestId('prefix-prediction').waitFor();});
  await step('last coordinate-pair cell',async()=>{await page.getByLabel('矩阵行',{exact:true}).fill('2559');await page.getByLabel('矩阵列',{exact:true}).fill('2559');await page.getByRole('button',{name:'读取全矩阵切片'}).click();await page.getByTestId('prefix-matrix').waitFor();});
  for(const [run,width] of [['qwen4_confirmation','2560'],['qwen14','5120'],['glm4','4096']])await step(run,async()=>{await page.getByLabel('前缀运行').selectOption(run);await settle();await waitField();if(await page.getByTestId('prefix-field').getAttribute('width')!==width)throw Error(run+' width');await page.getByLabel('前缀语言').selectOption('zh');const options=await page.getByLabel('前缀样本').locator('option').evaluateAll(es=>es.map(e=>e.value));const sid=options.find(x=>x.includes('-zh-'));await page.getByLabel('前缀样本').selectOption(sid);await settle();await waitField();await page.getByTestId('prefix-field').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,run+'.png')});});
  await step('source full H12 and zscore',async()=>{await page.getByTestId('source-field').waitFor();if(await page.getByTestId('source-field').getAttribute('width')!=='2560')throw Error('source width');await page.getByLabel('来源归一化').selectOption('true');await settle();await page.getByTestId('source-field').waitFor();await page.getByLabel('来源坐标数',{exact:true}).fill('1');await page.getByLabel('来源起始坐标',{exact:true}).fill('2559');await settle();await page.getByTestId('source-field').waitFor();await page.getByTestId('source-field').click({position:{x:20,y:20}});await page.getByTestId('source-picked').waitFor();});
  await step('source frozen predictions',async()=>{await page.getByRole('button',{name:'来源规则冻结预测'}).click();await page.getByLabel('来源起始坐标',{exact:true}).fill('0');await page.getByLabel('来源坐标数',{exact:true}).fill('2560');await settle();await page.getByTestId('source-prediction').waitFor();await page.getByLabel('来源规则',{exact:true}).selectOption('absolute_history');await page.getByLabel('来源锚点').selectOption('1');await settle();await page.getByTestId('source-field').waitFor();});
  await step('source fresh64 and relation profiles',async()=>{await page.getByLabel('来源集',{exact:true}).selectOption('fresh');await settle();await page.getByTestId('source-field').waitFor();await page.getByRole('button',{name:'来源规则冻结预测'}).click();await settle();await page.getByTestId('source-prediction').waitFor();await page.getByRole('button',{name:'关系条件全坐标'}).click();await settle();await page.getByTestId('source-field').waitFor();if(await page.getByTestId('source-field').getAttribute('height')!=='14')throw Error('relation count');await page.getByTestId('source-field').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'source_relations.png')});});
  await step('eight science figures',async()=>{const figs=page.locator('figure img');if(await figs.count()!==8)throw Error('figures count');for(const f of await figs.all())await f.scrollIntoViewIfNeeded();await settle();if(!(await figs.evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0))))throw Error('image loading');});
  await step('legacy atlas regression',async()=>{await page.goto('http://127.0.0.1:5173/rdc');await page.getByRole('heading',{name:'语言结构 · 原生坐标 · 提取算法'}).waitFor({timeout:30000});await page.getByRole('link',{name:'共同自然前缀图谱 ↗'}).waitFor();});
  if(errors.length)throw Error(JSON.stringify(errors));
  fs.writeFileSync(path.join(out,'browser_checks.json'),JSON.stringify({passed:true,timestamp:new Date().toISOString(),actions,page_errors:errors},null,2));console.log('PREFIX_BROWSER_PASS',actions.length);
 }catch(e){await page.screenshot({path:path.join(out,'browser_failure.png')});fs.writeFileSync(path.join(out,'browser_failure.json'),JSON.stringify({message:e.message,actions,errors},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
