"""Update MEMO with Phase 432b results"""
import sys
from datetime import datetime

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

now = datetime.now().strftime("%Y-%m-%d %H:%M")
time_short = now.split()[1]

lines = []
lines.append("")
lines.append("## Phase 432b: Property Transport with W_E Directions [2026-06-10 %s]" % time_short)
lines.append("")
lines.append("### 实验原理")
lines.append("")
lines.append("Phase 432发现W_U属性方向注入无效，但可能是因为W_U是读出方向。本实验使用W_E属性方向（如W_E(red)-W_E(green)），与类别方向在相同空间中计算，进行公平比较。")
lines.append("")
lines.append("### 核心数据")
lines.append("")
lines.append("#### 1. W_E与W_U属性方向的余弦相似度")
lines.append("")
lines.append("| 属性 | Qwen3 | GLM4 | DS7B |")
lines.append("|------|-------|------|------|")
lines.append("| red | 0.634 | 0.028 | 0.006 |")
lines.append("| sweet | 0.786 | 0.009 | 0.016 |")
lines.append("| sharp | 0.730 | -0.017 | 0.031 |")
lines.append("| fast | 0.574 | -0.015 | 0.010 |")
lines.append("| metal | 0.644 | 0.012 | 0.020 |")
lines.append("")
lines.append("Qwen3的W_E和W_U属性方向中等相关(0.57-0.79)，GLM4和DS7B几乎正交(0.00-0.03)")
lines.append("")
lines.append("#### 2. W_E属性方向注入效果（对比类别方向Phase 430）")
lines.append("")
lines.append("| 对象/属性 | Qwen3 pos_delta | GLM4 pos_delta | DS7B pos_delta | 类别delta(Phase430) |")
lines.append("|-----------|-----------------|----------------|----------------|---------------------|")
lines.append("| apple/red | -0.133 | -0.044 | -0.001 | -0.82 |")
lines.append("| apple/sweet | +0.015 | -0.005 | ~0 | -0.82 |")
lines.append("| knife/sharp | +0.002 | -0.066 | +0.0001 | -0.82 |")
lines.append("| car/fast | +0.003 | -0.001 | ~0 | -0.82 |")
lines.append("")
lines.append("所有W_E属性方向注入仍然无效！类别方向delta是属性方向的50-500倍")
lines.append("")
lines.append("#### 3. 所有属性注入的top_shift都是'a'或'one'")
lines.append("")
lines.append("模型从属性补全(The apple is red)切换到限定词输出(The apple is a fruit/one of...)")
lines.append("这表明属性方向注入意外激活了类别路径而非属性路径")
lines.append("")
lines.append("#### 4. 属性方向运输cosine（中层/last_pos）")
lines.append("")
lines.append("| 模型 | cos_with_prop | cos_with_cat |")
lines.append("|------|---------------|--------------|")
lines.append("| Qwen3 | 0.01-0.05 | 0.01-0.04 |")
lines.append("| GLM4 | -0.02-0.01 | -0.04-0.02 |")
lines.append("| DS7B | 0.01-0.06 | -0.05-0.05 |")
lines.append("")
lines.append("属性方向在运输后几乎完全消失，远弱于类别方向(cos=0.1-0.4)")
lines.append("")
lines.append("### 客观现象总结")
lines.append("")
lines.append("1. W_E属性方向注入也无效：问题不在于W_E vs W_U，而在于类别vs属性")
lines.append("2. 三模型一致：属性方向delta比类别方向小50-500倍")
lines.append("3. 属性注入意外激活类别路径：top_shift全是'a'/'one'")
lines.append("4. 属性方向运输后消失：cos_with_prop接近0")
lines.append("5. W_E和W_U属性方向的余弦：Qwen3=0.6-0.8, GLM4/DS7B=0.0-0.03")
lines.append("")
lines.append("### 严格审视")
lines.append("")
lines.append("硬伤1：属性方向定义可能不对。W_E(red)-W_E(green)是两个词embedding的差，不是'红色属性'在模型内部的表示方向。")
lines.append("硬伤2：属性信息可能不由线性方向编码。颜色、味道等可能是非线性/上下文依赖的表示。")
lines.append("硬伤3：类别是模型必须预测的高层语义（直接出现在训练目标中），属性可能只是隐含的关联。")
lines.append("硬伤4：属性方向可能需要从上下文化的表示中提取，而非静态embedding。")
lines.append("")
lines.append("### 关键洞察")
lines.append("")
lines.append("核心发现：自然运输机制是类别特异的。属性信息不以简单的线性方向存在于embedding空间中。")
lines.append("")
lines.append("可能的解释：")
lines.append("1. 类别方向是'一阶'语义特征：模型在训练中显式学习类别区分")
lines.append("2. 属性方向是'二阶'语义特征：属性通过类别中介间接影响输出")
lines.append("3. 属性信息可能分散在多个维度上，需要非线性组合才能激活")
lines.append("4. 或者属性信息根本不在embedding空间，而是在上下文化的激活中产生")
lines.append("")
lines.append("物理图像：")
lines.append("```")
lines.append("[Category] 线性可分 -> 单方向可操控 -> 自然运输有效")
lines.append("[Property] 非线性分布 -> 需要多维组合 -> 线性注入无效")
lines.append("```")

memo_text = "\n".join(lines)

memo_path = "d:/Ai2050/TransformerLens-Project/research/glm5/docs/AGI_GLM5_MEMO.md"
with open(memo_path, 'a', encoding='utf-8') as f:
    f.write(memo_text)

print("MEMO updated with Phase 432b at %s" % now)
