"""Update AGI_GLM5_MEMO.md with Phase 432-433 results"""
import sys
from datetime import datetime

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

now = datetime.now().strftime("%Y-%m-%d %H:%M")
time_short = now.split()[1]

lines = []
lines.append("")
lines.append("## Phase 433: Transport Operator Stability [2026-06-10 %s]" % time_short)
lines.append("")
lines.append("### 实验原理")
lines.append("")
lines.append("Phase 430建立了自然运输方向概念，但未验证运输算子是否跨对象稳定。本实验回答核心问题：同类对象的运输方向是否一致？")
lines.append("")
lines.append("方法：")
lines.append("1. 对同类别不同对象（如apple/orange/lemon）注入相同的类别方向")
lines.append("2. 记录每层的delta_l = h_l(perturbed) - h_l(clean)")
lines.append("3. 计算同类别对象间的delta_l余弦相似度（within-category cosine）")
lines.append("4. 计算跨类别对象间的delta_l余弦相似度（cross-category cosine）")
lines.append("5. 两者之差（gap）衡量类别特异性的强度")
lines.append("")
lines.append("### 核心数据")
lines.append("")
lines.append("#### 1. 同类别运输方向余弦相似度（last_pos位置，跨模型对比）")
lines.append("")
lines.append("| 层位 | Qwen3 | GLM4 | DS7B |")
lines.append("|------|-------|------|------|")
lines.append("| L0/last | 0.65-0.98 | 0.97-1.00 | 0.93-0.98 |")
lines.append("| 早层(L3-7)/last | 0.59-0.73 | 0.93-0.97 | 0.83-0.93 |")
lines.append("| 中层(L10-16)/last | 0.28-0.68 | 0.83-0.96 | 0.35-0.69 |")
lines.append("| 深层(L24-31)/last | 0.12-0.50 | 0.82-0.92 | 0.38-0.46 |")
lines.append("")
lines.append("#### 2. 跨类别gap（within - cross），last_pos位置")
lines.append("")
lines.append("| 层位 | Qwen3 | GLM4 | DS7B |")
lines.append("|------|-------|------|------|")
lines.append("| L0/last | +0.129 | +0.098 | +1.019 |")
lines.append("| 早层/last | +0.308-0.464 | +0.268 | +0.378-0.667 |")
lines.append("| 中层/last | +0.248-0.354 | +0.583-0.627 | +0.280-0.305 |")
lines.append("| 深层/last | +0.201-0.310 | +0.627-0.713 | +0.032-0.298 |")
lines.append("")
lines.append("DS7B L0/last: cross-category cosine = -0.045（跨类别方向反转！）")
lines.append("")
lines.append("#### 3. obj位置同类别余弦 = 1.000（三模型一致，平凡结果）")
lines.append("")
lines.append("### 客观现象总结")
lines.append("")
lines.append("1. 同类别对象共享运输方向：within-category cosine在所有层都远高于cross-category")
lines.append("2. 所有跨类别gap都是正的：每个层/位置组合都存在类别特异性")
lines.append("3. GLM4的运输一致性最高：within-cat cosine > 0.8在几乎所有层")
lines.append("4. 运输一致性随深度递减：早层高（0.6-1.0），深层低（0.1-0.5）")
lines.append("5. obj位置cosine=1.000是平凡的：因为注入方向相同，obj位置delta必然相同")
lines.append("6. 真正有意义的是last位置：显示类别信息如何从obj搬运到last")
lines.append("")
lines.append("### 严格审视")
lines.append("")
lines.append("硬伤1：obj位置cos=1.000是trivial的，对同一对象注入完全相同的方向，obj位置的delta必然相同。")
lines.append("硬伤2：R1每类只有2-3个对象，fruit和tool只有2个对象（lemon/spoon是多token），需要更多单token对象。")
lines.append("硬伤3：类别方向本身就是统计均值差，运输方向的类别特异性可能只是反映了注入方向的类别特异性。")
lines.append("硬伤4：没有消融实验，仅证明相关性，未证明因果性。")
lines.append("")
lines.append("### 关键洞察")
lines.append("")
lines.append("核心发现：自然运输方向具有类别特异性，运输算子T_{0->l}是类别依赖的。")
lines.append("")
lines.append("物理图像：")
lines.append("```")
lines.append("T_{0->l}^{fruit}(d_fruit) -> similar direction for all fruits")
lines.append("T_{0->l}^{fruit}(d_fruit) != T_{0->l}^{animal}(d_animal) at last_pos")
lines.append("```")
lines.append("")
lines.append("运输一致性递减模式：")
lines.append("- L0/last: 高（0.65-0.98）- 初始运输保持方向")
lines.append("- 早层/last: 中高（0.6-0.9）- 注意力搬运初期一致")
lines.append("- 中层/last: 中等（0.3-0.7）- 开始分化")
lines.append("- 深层/last: 低（0.1-0.5）- 深层精炼后类别信号被重新编码")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Phase 432: Property Natural Transport [2026-06-10 %s]" % time_short)
lines.append("")
lines.append("### 实验原理")
lines.append("")
lines.append("Phase 430验证了类别方向的自然运输。本实验测试运输机制是否泛化到属性（property）。")
lines.append("")
lines.append("方法：")
lines.append("1. 定义对象属性：apple->red/sweet, dog->brown/furry, knife->sharp/metal, car->fast/engine")
lines.append("2. 使用W_U属性方向注入（W_U['red']列向量）")
lines.append("3. 测量属性注入对输出的影响")
lines.append("4. 跟踪属性方向的层间运输")
lines.append("")
lines.append("### 核心数据")
lines.append("")
lines.append("#### 1. W_U属性方向注入效果（top_shift = 最大概率变化）")
lines.append("")
lines.append("| 对象 | 属性 | Qwen3 | GLM4 | DS7B |")
lines.append("|------|------|-------|------|------|")
lines.append("| apple | red | -0.133 | -0.043 | -0.002 |")
lines.append("| apple | sweet | +0.008 | -0.005 | ~0 |")
lines.append("| dog | brown | +0.014 | -0.004 | ~0 |")
lines.append("| dog | furry | ~0 | ~0 | ~0 |")
lines.append("| knife | sharp | -0.004 | -0.062 | +0.0002 |")
lines.append("| knife | metal | ~0 | ~0 | ~0 |")
lines.append("| car | fast | +0.002 | -0.001 | ~0 |")
lines.append("| car | engine | +0.0004 | ~0 | +0.0005 |")
lines.append("")
lines.append("所有属性注入效果都是负的或可忽略！对比类别注入：delta可达-0.82")
lines.append("")
lines.append("#### 2. W_U属性方向与类别方向的余弦（cos(cat_dir)）")
lines.append("")
lines.append("所有属性方向与类别方向的余弦都在+/-0.09以内，几乎正交。")
lines.append("")
lines.append("#### 3. 属性方向运输后的cosine（cos_with_inject）")
lines.append("")
lines.append("| 模型 | L0/last | 中层/last | 深层/last |")
lines.append("|------|---------|-----------|-----------|")
lines.append("| Qwen3 | 0.07-0.31 | 0.03-0.15 | 0.01-0.03 |")
lines.append("| GLM4 | -0.03-0.06 | 0.00-0.04 | -0.02-0.01 |")
lines.append("| DS7B | -0.01-0.05 | 0.02-0.04 | 0.00-0.04 |")
lines.append("")
lines.append("W_U属性方向在运输后几乎完全消失（cos约等于0）")
lines.append("")
lines.append("### 客观现象总结")
lines.append("")
lines.append("1. W_U属性方向在embedding层注入完全无效：三模型一致")
lines.append("2. 属性注入效果多为负值：注入red方向反而降低了red的概率")
lines.append("3. 运输后W_U方向消失：cosine从0.07降到接近0")
lines.append("4. 对比类别方向（Phase 430）：类别方向运输后cosine从0.4降到0.03（L0到L7），但仍然能产生切换")
lines.append("")
lines.append("### 严格审视")
lines.append("")
lines.append("硬伤1：方法学不对称！类别方向 = W_E(fruit_center) - W_E(animal_center)【输入空间】，属性方向 = W_U['red']【输出/读出空间】。两者不可直接比较！")
lines.append("硬伤2：W_U是读出方向，不是编码方向。W_U['red']告诉模型当内部状态像这样时输出red，但不代表内部状态应该像这样来表示redness。")
lines.append("硬伤3：需要W_E属性方向测试。正确方法：red_objects - not_red_objects在W_E空间中的差，类似类别方向的计算。")
lines.append("")
lines.append("### 关键洞察")
lines.append("")
lines.append("核心发现：输出空间的读出方向(W_U)和输入空间的编码方向(W_E)是根本不同的东西。")
lines.append("")
lines.append("```")
lines.append("W_E difference（编码方向）：")
lines.append("  水果在embedding空间朝这个方向")
lines.append("  注入后模型内部确实产生类别信号")
lines.append("")
lines.append("W_U column（读出方向）：")
lines.append("  当残差流指向这个方向时输出red")
lines.append("  注入后方向在运输中消失，不影响输出")
lines.append("```")
lines.append("")
lines.append("这恰好是自然运输概念预测的：模型内部的方向不是固定的，而是被层间计算变换的。W_U读出方向是最终层的方向，不是输入层的方向。")
lines.append("")
lines.append("物理图像：")
lines.append("```")
lines.append("[Input] W_E difference (encoding direction)")
lines.append("  -> model layers ROTATE and TRANSPORT it")
lines.append("  -> [Output] W_U column (readout direction)")
lines.append("")
lines.append("Injecting W_U at input = applying the OUTPUT rotation to INPUT space")
lines.append("= wrong end of the pipeline")
lines.append("```")
lines.append("")
lines.append("### 下一步")
lines.append("")
lines.append("1. Phase 432b: W_E属性方向测试 - 用embedding空间的属性差（如sweet-bitter）替代W_U方向")
lines.append("2. Phase 434: 严格因果追踪重做 - 改进corrupt-restore方法")
lines.append("3. Phase 435: 范数增长机制 - 分析DS7B范数异常")
lines.append("4. Phase 436: 组件路径分析 - attention vs MLP对运输的贡献")

memo_text = "\n".join(lines)

# Append to MEMO
memo_path = "d:/Ai2050/TransformerLens-Project/research/glm5/docs/AGI_GLM5_MEMO.md"
with open(memo_path, 'a', encoding='utf-8') as f:
    f.write(memo_text)

print("MEMO updated at %s" % now)
print("Added Phase 432 and 433 results")
